// Le stringhe dell'editor dei disegni.
//
// Arrivano con la superficie del disegno, che la shell carica con un
// `import()` quando si apre un disegno (`lazy.ts`): chi non ne apre uno non le
// scarica. La lingua, la scala di ripiego, i nomi fra graffe e i plurali sono
// quelli della shell (`catalog` in `i18n/strings.ts`). Le stringhe che la
// shell mostra prima che la superficie arrivi, come gli avvisi di un file che
// non si apre, restano nel catalogo della shell.

import { catalog } from "../../i18n/strings";

/// Il catalogo italiano, che è anche la forma degli altri.
const IT = {
  "draw.toolbar": "Strumenti di disegno",
  "draw.surface": "Foglio del disegno",
  "draw.tools": "Strumento",
  "draw.colors": "Colore",
  "draw.widths": "Spessore",
  "draw.edit": "Modifica",
  "draw.view": "Vista",
  "draw.tool.select": "Selezione",
  "draw.tool.select.hint": "Tocca un oggetto per sceglierlo e trascinalo per spostarlo; trascina sul vuoto per sceglierne più d’uno con un riquadro. Con Maiusc aggiungi o togli oggetti dalla selezione; le frecce spostano di 1, con Maiusc di 10.",
  "draw.tool.pen": "Penna",
  "draw.tool.pen.hint": "Disegna a mano libera; con la penna lo spessore segue la pressione.",
  "draw.tool.highlighter": "Evidenziatore",
  "draw.tool.highlighter.hint": "Passa sopra ciò che vuoi mettere in risalto: il segno è largo, di spessore costante, e lascia vedere ciò che copre.",
  "draw.tool.eraser": "Gomma",
  "draw.tool.eraser.hint": "Toglie gli oggetti interi che attraversi.",
  "draw.tool.rect": "Rettangolo",
  "draw.tool.rect.hint": "Trascina per disegnare un rettangolo; con Maiusc un quadrato.",
  "draw.tool.ellipse": "Ellisse",
  "draw.tool.ellipse.hint": "Trascina per disegnare un’ellisse; con Maiusc un cerchio.",
  "draw.tool.line": "Linea",
  "draw.tool.line.hint": "Trascina per disegnare una linea; con Maiusc l’angolo va a passi di 15°.",
  "draw.tool.arrow": "Freccia",
  "draw.tool.arrow.hint": "Trascina per disegnare una freccia; con Maiusc l’angolo va a passi di 15°.",
  "draw.color.black": "Nero",
  "draw.color.blue": "Blu",
  "draw.color.vermilion": "Vermiglio",
  "draw.color.green": "Verde",
  "draw.color.purple": "Porpora",
  "draw.color.orange": "Arancione",
  "draw.color.sky": "Azzurro",
  "draw.color.yellow": "Giallo",
  "draw.color.custom": "Personalizzato {code}",
  "draw.color.custom.light": "Personalizzato {code}, chiaro: sulla carta bianca si legge poco",
  "draw.color.more": "Altro colore…",
  "draw.color.dialog": "Colore personalizzato",
  "draw.color.code": "Codice del colore",
  "draw.width.thin": "Sottile",
  "draw.width.medium": "Medio",
  "draw.width.thick": "Spesso",
  "draw.undo": "Annulla",
  "draw.redo": "Ripeti",
  "draw.delete": "Elimina la selezione",
  "draw.zoom_in": "Ingrandisci",
  "draw.zoom_out": "Riduci",
  "draw.zoom_reset": "{zoom}: riporta lo zoom al 100%",
  "draw.fit": "Mostra tutto il disegno",
  "draw.title": "Che cosa hai disegnato?",
  "draw.title.placeholder": "Per esempio: la rete di casa",
  "draw.objects.one": "Il disegno ha {count} oggetto.",
  "draw.objects.other": "Il disegno ha {count} oggetti.",
  "draw.selected.none": "Nessun oggetto scelto.",
  "draw.selected.one": "{count} oggetto scelto.",
  "draw.selected.other": "{count} oggetti scelti.",
  "draw.deleted.one": "{count} oggetto eliminato.",
  "draw.deleted.other": "{count} oggetti eliminati.",
  "draw.erased.one": "{count} oggetto cancellato.",
  "draw.erased.other": "{count} oggetti cancellati.",
  "draw.moved.one": "{count} oggetto spostato.",
  "draw.moved.other": "{count} oggetti spostati.",
  "draw.added.stroke": "Tratto aggiunto.",
  "draw.added.highlight": "Evidenziatura aggiunta.",
  "draw.added.rect": "Rettangolo aggiunto.",
  "draw.added.ellipse": "Ellisse aggiunta.",
  "draw.added.line": "Linea aggiunta.",
  "draw.added.arrow": "Freccia aggiunta.",
  "draw.announce.tool": "Strumento: {tool}.",
  "draw.announce.color": "Colore: {color}.",
  "draw.rejected": "Modifica non applicata: {reason}.",
  "draw.reason.missing_target": "l’oggetto non c’è più",
  "draw.reason.missing_parent": "il livello non c’è più",
  "draw.reason.duplicate_id": "un identificativo è già in uso",
  "draw.reason.invalid": "la modifica non è valida",
  "draw.reason.locked": "l’oggetto è in un livello bloccato",
  "draw.reason.foreign": "la parte viene da un altro programma e FubDraw la lascia com’è",
  "draw.reason.limit": "il disegno ha raggiunto la dimensione massima",
  "draw.reason.read_only": "il disegno è in sola lettura",
  "draw.undone": "Annullato: {action}.",
  "draw.redone": "Ripetuto: {action}.",
  "draw.undo.failed": "Impossibile annullare «{action}»: il disegno è cambiato nel frattempo.",
  "draw.redo.failed": "Impossibile ripetere «{action}»: il disegno è cambiato nel frattempo.",
  "draw.no_layer": "Ogni livello è bloccato o nascosto: non c’è dove disegnare.",
  "draw.ink_failed": "Impossibile salvare il tratto.",
  "draw.action.stroke": "Tratto",
  "draw.action.highlight": "Evidenziatura",
  "draw.action.move": "Spostamento",
  "draw.action.erase": "Cancellazione",
  "draw.action.delete": "Eliminazione",
  "draw.action.title": "Titolo",
  "draw.action.adopt": "Disegno reso modificabile",
  "draw.adopted": "Ora il disegno si modifica.",
  "draw.kind.layer": "Livello",
  "draw.kind.group": "Gruppo",
  "draw.kind.link": "Collegamento",
  "draw.kind.stroke": "Tratto",
  "draw.kind.highlighter": "Evidenziatura",
  "draw.kind.path": "Tracciato",
  "draw.kind.circle": "Cerchio",
  "draw.kind.polyline": "Spezzata",
  "draw.kind.polygon": "Poligono",
  "draw.kind.text": "Testo",
  "draw.kind.image": "Immagine",
  "draw.describe.named": "{kind} «{name}»",
  "draw.describe.link": "{link} a «{note}»",
  "draw.describe.parts.one": "{count} oggetto",
  "draw.describe.parts.other": "{count} oggetti",
  "draw.state.locked": "bloccato",
  "draw.state.hidden": "nascosto",
  "draw.objects": "Oggetti",
  "draw.objects.empty": "Il disegno è vuoto.",
  "draw.surface.hint": "Le frecce muovono il cursore o la selezione; Spazio preme e rilascia; Tab passa all’oggetto dopo; Invio apre le proprietà; ? elenca i tasti.",
  "draw.properties": "Proprietà",
  "draw.properties.selection": "Posizione e misure",
  "draw.properties.document": "Proprietà del disegno",
  "draw.field.width": "Larghezza",
  "draw.field.height": "Altezza",
  "draw.field.title": "Titolo",
  "draw.field.desc": "Descrizione",
  "draw.field.page_width": "Larghezza della pagina",
  "draw.field.page_height": "Altezza della pagina",
  "draw.keys": "Tasti del disegno",
  "draw.keys.tools": "Strumenti",
  "draw.keys.cursor": "Disegnare da tastiera",
  "draw.keys.cursor.move": "Muove il cursore: 10 px, 50 con Maiusc, 1 con Ctrl o ⌘",
  "draw.keys.cursor.press": "Preme, e poi rilascia",
  "draw.keys.cancel": "Annulla il gesto",
  "draw.keys.nudge": "Sposta la selezione di 1, con Maiusc di 10",
  "draw.keys.resize": "Ridimensiona la selezione di 1, con Maiusc di 10",
  "draw.keys.walk": "L’oggetto dopo o prima",
  "draw.keys.ends": "Il primo o l’ultimo oggetto",
  "draw.keys.all": "Sceglie tutto",
  "draw.keys.deselect": "Toglie la selezione",
  "draw.keys.actual": "Zoom al 100%",
  "draw.cursor.at": "x {x}, y {y}",
  "draw.cursor.down": "Premuto: le frecce tracciano, Spazio rilascia, Esc annulla.",
  "draw.cursor.up": "Rilasciato.",
  "draw.resized": "Misure: {width} × {height}.",
  "draw.walk": "{object}, {index} di {count}.",
  "draw.action.resize": "Ridimensionamento",
  "draw.keys.paste": "Incolla un’immagine",
  "draw.action.image": "Immagine",
  "draw.added.image.one": "Immagine aggiunta.",
  "draw.added.image.other": "{count} immagini aggiunte.",
  "draw.image.heavy.one": "Immagine troppo pesante",
  "draw.image.heavy.other": "Immagini troppo pesanti",
  "draw.image.large": "L’immagine pesa {size}, e in un disegno un’immagine può pesare al più {limit}. Ridurla? Avrà meno pixel, ma la stessa misura sul foglio.",
  "draw.image.shared": "Le immagini pesano {size} in tutto, e quelle aggiunte insieme possono pesare al più {limit}. Ridurle? Avranno meno pixel, ma la stessa misura sul foglio.",
  "draw.image.room": "Nel disegno resta posto per {limit} di immagini, e ne servono {size}. Ridurre? Le immagini avranno meno pixel, ma la stessa misura sul foglio.",
  "draw.image.reduce": "Riduci",
  "draw.image.reducing": "Riduzione dell’immagine…",
  "draw.image.unreadable": "Non è un’immagine che il disegno sa leggere.",
  "draw.image.full": "Il disegno è vicino al limite di {limit}: un’altra immagine non ci sta.",
  "draw.image.failed": "Impossibile ridurre l’immagine.",
  "draw.arrange": "Disponi",
  "draw.duplicate": "Duplica",
  "draw.group": "Raggruppa",
  "draw.ungroup": "Separa",
  "draw.order": "Ordine",
  "draw.order.front": "Porta in primo piano",
  "draw.order.forward": "Porta avanti",
  "draw.order.backward": "Porta indietro",
  "draw.order.back": "Porta in secondo piano",
  "draw.align": "Allinea e distribuisci",
  "draw.align.left": "Allinea a sinistra",
  "draw.align.center": "Allinea al centro",
  "draw.align.right": "Allinea a destra",
  "draw.align.top": "Allinea in alto",
  "draw.align.middle": "Allinea in mezzo",
  "draw.align.bottom": "Allinea in basso",
  "draw.align.to_page": "{action}, rispetto alla pagina",
  "draw.distribute.x": "Distribuisci orizzontalmente",
  "draw.distribute.y": "Distribuisci verticalmente",
  "draw.distribute.few": "Servono almeno tre oggetti.",
  "draw.action.duplicate": "Duplicazione",
  "draw.action.order": "Cambio d’ordine",
  "draw.action.group": "Raggruppamento",
  "draw.action.ungroup": "Separazione",
  "draw.action.align": "Allineamento",
  "draw.action.distribute": "Distribuzione",
  "draw.duplicated.one": "{count} oggetto duplicato.",
  "draw.duplicated.other": "{count} oggetti duplicati.",
  "draw.duplicate.foreign": "Non duplicato: un oggetto ha parti di un altro programma, che FubDraw non sa copiare.",
  "draw.ordered.front": "In primo piano.",
  "draw.ordered.forward": "Un posto più avanti.",
  "draw.ordered.backward": "Un posto più indietro.",
  "draw.ordered.back": "In secondo piano.",
  "draw.grouped": "Gruppo di {count} oggetti.",
  "draw.group.few": "Per un gruppo servono almeno due oggetti.",
  "draw.ungrouped.one": "{count} gruppo separato.",
  "draw.ungrouped.other": "{count} gruppi separati.",
  "draw.ungroup.none": "Fra gli oggetti scelti non c’è un gruppo.",
  "draw.ungroup.foreign": "Non separato: il gruppo ha parti di un altro programma, che non seguirebbero la sua posizione o il suo stile.",
  "draw.aligned.one": "{count} oggetto allineato.",
  "draw.aligned.other": "{count} oggetti allineati.",
  "draw.distributed": "{count} oggetti distribuiti.",
  "draw.unchanged": "È già così: niente da cambiare.",
  "draw.keys.arrange": "Va alla barra della selezione",
  "draw.surface.hint.arrange": "Le frecce muovono il cursore o la selezione; Spazio preme e rilascia; Tab passa all’oggetto dopo; Invio apre le proprietà; con una selezione, Alt+F10 porta ai comandi per disporla; ? elenca i tasti.",
  "draw.layers": "Livelli",
  "draw.layers.current": "Livelli: si disegna in «{name}»",
  "draw.layers.none": "Livelli: il disegno non ne ha",
  "draw.layers.none.short": "Nessun livello",
  "draw.layer.default": "Livello {n}",
  "draw.layer.unnamed": "Livello senza nome",
  "draw.layer.new": "Nuovo livello",
  "draw.layer.rename": "Rinomina «{name}»…",
  "draw.layer.hide": "Nascondi «{name}»",
  "draw.layer.show": "Mostra «{name}»",
  "draw.layer.lock": "Blocca «{name}»",
  "draw.layer.unlock": "Sblocca «{name}»",
  "draw.layer.up": "Sposta «{name}» su",
  "draw.layer.down": "Sposta «{name}» giù",
  "draw.layer.delete": "Elimina «{name}»",
  "draw.layer.delete.last": "È l’unico livello.",
  "draw.layer.delete.locked": "È bloccato: sbloccalo per eliminarlo.",
  "draw.layer.rename.dialog": "Rinomina il livello",
  "draw.layer.name": "Nome del livello",
  "draw.layer.chosen": "Si disegna in «{name}».",
  "draw.layer.locked_here": "«{name}» è bloccato: sbloccalo, o scegli un altro livello, per disegnare.",
  "draw.layer.hidden_here": "«{name}» è nascosto: mostralo, o scegli un altro livello, per disegnare.",
  "draw.layer.flat": "«{name}» ha una trasformazione che lo schiaccia: non ci si disegna.",
  "draw.layer.added": "Livello «{name}» creato: si disegna lì.",
  "draw.layer.renamed": "Il livello ora si chiama «{name}».",
  "draw.layer.hidden": "«{name}» nascosto.",
  "draw.layer.shown": "«{name}» di nuovo visibile.",
  "draw.layer.locked": "«{name}» bloccato.",
  "draw.layer.unlocked": "«{name}» sbloccato.",
  "draw.layer.moved_up": "«{name}» ora sta sopra «{other}».",
  "draw.layer.moved_down": "«{name}» ora sta sotto «{other}».",
  "draw.layer.deleted": "«{name}» eliminato.",
  "draw.layer.deleted.one": "«{name}» eliminato, con {count} oggetto.",
  "draw.layer.deleted.other": "«{name}» eliminato, con {count} oggetti.",
  "draw.action.layer_add": "Nuovo livello",
  "draw.action.layer_rename": "Nome del livello",
  "draw.action.layer_hide": "Livello nascosto",
  "draw.action.layer_show": "Livello mostrato",
  "draw.action.layer_lock": "Livello bloccato",
  "draw.action.layer_unlock": "Livello sbloccato",
  "draw.action.layer_order": "Ordine dei livelli",
  "draw.action.layer_delete": "Eliminazione del livello",
  "draw.action.into_layer": "Spostamento in un livello",
  "draw.into_layer": "Sposta in un livello",
  "draw.into_layer.here": "Gli oggetti scelti sono già qui.",
  "draw.moved_to_layer.one": "{count} oggetto spostato in «{name}».",
  "draw.moved_to_layer.other": "{count} oggetti spostati in «{name}».",
  "draw.state.current": "corrente",
  "draw.page_grid": "Pagina e griglia",
  "draw.grid.show": "Mostra la griglia",
  "draw.grid.snap": "Aggancia alla griglia",
  "draw.grid.snap.free": "Tieni premuto {key} mentre trascini per posare libero.",
  "draw.grid.step": "Passo di {step}",
  "draw.grid.shown": "Griglia visibile.",
  "draw.grid.hidden": "Griglia nascosta.",
  "draw.grid.snap.on": "Aggancio alla griglia acceso.",
  "draw.grid.snap.off": "Aggancio alla griglia spento.",
  "draw.grid.stepped": "Passo della griglia: {step}.",
  "draw.page.fit": "Adatta la pagina al disegno",
  "draw.page.fit.empty": "Il disegno è vuoto.",
  "draw.page.fit.already": "La pagina è già adattata al disegno.",
  "draw.page.fitted": "Pagina adattata: {width} × {height}.",
  "draw.action.fit_page": "Pagina adattata al disegno",
  "draw.keys.grid": "Griglia",
  "draw.keys.grid.show": "Mostra o nasconde la griglia",
  "draw.keys.grid.snap": "Accende o spegne l’aggancio alla griglia",
  "draw.keys.grid.free": "Tenuto mentre si trascina: posa libero, fuori dalla griglia",
  "draw.keys.cursor.move.grid": "Muove il cursore alla riga seguente della griglia, a cinque righe con Maiusc; libero di 1 px con Ctrl o ⌘",
  "draw.keys.nudge.grid": "Sposta la selezione alla riga seguente della griglia, a cinque righe con Maiusc",
  "draw.keys.resize.grid": "Ridimensiona la selezione fino alla riga seguente della griglia, a cinque righe con Maiusc",
  "draw.tool.text": "Testo",
  "draw.tool.text.hint": "Tocca il foglio per scrivere un testo, o un testo per cambiarlo. Invio va a capo; Esc conclude.",
  "draw.sizes": "Dimensione",
  "draw.size.small": "Piccolo",
  "draw.size.medium": "Medio",
  "draw.size.large": "Grande",
  "draw.text.new": "Testo nuovo",
  "draw.text.change": "Testo",
  "draw.text.hint": "Invio va a capo; Esc, Tab o {key}+Invio concludono.",
  "draw.text.edit": "Modifica il testo",
  "draw.action.text": "Testo",
  "draw.action.text_edit": "Modifica del testo",
  "draw.added.text": "Testo aggiunto.",
  "draw.text.edited": "Testo modificato.",
  "draw.text.none": "Scegli un testo da modificare.",
  "draw.keys.text": "Testo",
  "draw.keys.text.write": "Con lo strumento Testo: scrive dov’è il cursore, o cambia il testo che c’è",
  "draw.keys.text.edit": "Modifica il testo scelto",
  "draw.keys.text.newline": "Va a capo, mentre si scrive",
  "draw.keys.text.finish": "Conclude il testo, mentre si scrive",
  "draw.link": "Collega a una nota…",
  "draw.link.change": "Cambia il collegamento…",
  "draw.link.open": "Apri «{note}»",
  "draw.unlink": "Togli il collegamento",
  "draw.action.link": "Collegamento",
  "draw.action.relink": "Cambio del collegamento",
  "draw.action.unlink": "Rimozione del collegamento",
  "draw.linked": "Collegato a «{note}».",
  "draw.relinked": "Ora il collegamento porta a «{note}».",
  "draw.unlinked.one": "{count} collegamento tolto.",
  "draw.unlinked.other": "{count} collegamenti tolti.",
  "draw.unlink.none": "Fra gli oggetti scelti non c’è un collegamento.",
  "draw.unlink.foreign": "Non tolto: il collegamento ha parti di un altro programma, che non seguirebbero la sua posizione o il suo stile.",
  "draw.link.nested": "Non collegato: fra gli oggetti scelti c’è già un collegamento, e un collegamento non ne contiene un altro. Toglilo prima, o sceglilo da solo per cambiarlo.",
  "draw.link.open.none": "Scegli un collegamento per aprire la sua nota.",
  "draw.keys.link": "Collega a una nota, o cambia il collegamento scelto",
  "draw.keys.link.open": "Apre la nota del collegamento scelto",
  "draw.level.essential": "Essenziale",
  "draw.level.standard": "Standard",
  "draw.level.expert": "Esperto",
  "draw.keys.from_level": "{group} · dal livello {level}",
  "draw.keys.more": "Il livello di adesso è «{level}». I tasti qui sotto valgono da un livello più alto, che si sceglie nelle Impostazioni, nel gruppo «Disegni».",
  "draw.attributes": "Attributi",
  "draw.attributes.subject": "{object}, elemento {tag}",
  "draw.attributes.none": "Scegli un oggetto per vederne gli attributi.",
  "draw.attributes.many": "Gli oggetti scelti sono {count}: scegline uno per vederne gli attributi.",
  "draw.attributes.name": "Attributo",
  "draw.attributes.value": "Valore",
  "draw.attributes.actions": "Togli",
  "draw.attributes.id.none": "senza id",
  "draw.attributes.remove": "Togli {key}",
  "draw.attributes.add.title": "Aggiungi un attributo",
  "draw.attributes.add.key": "Nome dell’attributo",
  "draw.attributes.add.value": "Valore di {key}",
  "draw.attributes.add": "Aggiungi",
  "draw.attributes.added": "{key} aggiunto.",
  "draw.attributes.changed": "{key} cambiato.",
  "draw.attributes.removed": "{key} tolto.",
  "draw.attributes.renamed": "Ora l’id è «{id}».",
  "draw.attributes.size": "Il valore è lungo {size} caratteri: qui se ne vedono i primi {shown}.",
  "draw.attributes.note.ink": "Viene dall’inchiostro del tratto: si cambia ridisegnandolo.",
  "draw.attributes.note.arrow": "Viene dalla geometria della freccia: si cambia spostandone le estremità.",
  "draw.attributes.note.fubdraw": "Lo scrive FubDraw.",
  "draw.attributes.note.link": "Si cambia con «Cambia il collegamento…».",
  "draw.attributes.note.image": "Dice da dove viene l’immagine, e qui si legge soltanto.",
  "draw.attributes.note.namespace": "È di un altro programma: FubDraw lo conserva com’è.",
  "draw.attributes.note.long": "È troppo lungo per cambiarlo qui.",
  "draw.attributes.problem.empty": "Scrivi un valore, o togli l’attributo.",
  "draw.attributes.problem.paint": "Ci vuole un colore come #0072b2, o none.",
  "draw.attributes.problem.length": "Ci vuole un numero, come 12 o -4.5.",
  "draw.attributes.problem.size": "Ci vuole un numero non negativo, come 12 o 0.5.",
  "draw.attributes.problem.opacity": "Ci vuole un numero da 0 a 1, come 0.5.",
  "draw.attributes.problem.dashes": "Ci vuole none, o delle lunghezze separate da spazi, come 4 2.",
  "draw.attributes.problem.keyword": "Ci vuole uno dei valori della scelta.",
  "draw.attributes.problem.family": "Ci vuole uno dei caratteri della scelta.",
  "draw.attributes.problem.transform": "Ci vuole una trasformazione SVG, come translate(10 20) o rotate(45).",
  "draw.attributes.problem.points": "Ci vogliono delle coppie di numeri, come 0,0 10,0 10,10.",
  "draw.attributes.problem.path": "Ci vuole un percorso SVG, come M0 0 L10 10.",
  "draw.attributes.problem.aspect": "Ci vuole un allineamento come xMidYMid, seguito se serve da meet o slice.",
  "draw.attributes.problem.identity": "È la trasformazione che non cambia niente: non c’è niente da aggiungere.",
  "draw.attributes.id.empty": "Un id non può essere vuoto.",
  "draw.attributes.id.long": "Un id ha al più {max} caratteri.",
  "draw.attributes.id.form": "Un id comincia con una lettera o _, e continua con lettere, cifre, _, . e -.",
  "draw.attributes.id.reserved": "Gli id che cominciano con fub- sono di FubDraw.",
  "draw.attributes.id.taken": "«{id}» è già l’id di un altro elemento.",
  "draw.attributes.id.cited": "Una parte di un altro programma cita «{id}»: cambiarlo romperebbe il riferimento.",
  "draw.action.attribute": "Modifica di un attributo",
  "draw.action.rename": "Cambio dell’id",
  "draw.keys.attributes.toggle": "Mostra o nasconde gli attributi dell’oggetto scelto",
  "draw.keys.attributes.apply": "Applica il valore scritto",
  "draw.keys.attributes.newline": "Va a capo, nei punti e nei percorsi",
  "draw.keys.attributes.revert": "Riporta il valore com’era; di nuovo, torna al foglio",
  "draw.outline": "Contorno",
  "draw.outline.solid": "Continuo",
  "draw.outline.dashed": "Tratteggiato",
  "draw.outline.dotted": "Punteggiato",
  "draw.outline.dashdot": "Tratto e punto",
  "draw.outline.custom": "Su misura: {value}",
  "draw.outline.butt": "Estremi piatti",
  "draw.outline.round_cap": "Estremi arrotondati",
  "draw.outline.square": "Estremi quadrati",
  "draw.outline.miter": "Angoli vivi",
  "draw.outline.round_join": "Angoli arrotondati",
  "draw.outline.bevel": "Angoli smussati",
  "draw.outline.none": "Nessun oggetto scelto ha un contorno.",
  "draw.outlined.one": "{style}: un contorno.",
  "draw.outlined.other": "{style}: {count} contorni.",
  "draw.action.dash": "Tratteggio",
  "draw.action.cap": "Estremi del contorno",
  "draw.action.join": "Angoli del contorno"
} as const;

/// Una chiave del catalogo del disegno.
export type DrawKey = keyof typeof IT;

/// L'inglese, completo per tipo come quello della shell.
const EN: Record<DrawKey, string> = {
  "draw.toolbar": "Drawing tools",
  "draw.surface": "Drawing sheet",
  "draw.tools": "Tool",
  "draw.colors": "Color",
  "draw.widths": "Width",
  "draw.edit": "Edit",
  "draw.view": "View",
  "draw.tool.select": "Select",
  "draw.tool.select.hint": "Tap an object to select it and drag it to move it; drag on empty space to select several with a box. Hold Shift to add or remove objects from the selection; arrow keys move by 1, with Shift by 10.",
  "draw.tool.pen": "Pen",
  "draw.tool.pen.hint": "Draw freehand; with a pen the width follows the pressure.",
  "draw.tool.highlighter": "Highlighter",
  "draw.tool.highlighter.hint": "Go over what you want to stand out: the mark is wide, of even width, and lets what it covers show through.",
  "draw.tool.eraser": "Eraser",
  "draw.tool.eraser.hint": "Removes the whole objects you cross.",
  "draw.tool.rect": "Rectangle",
  "draw.tool.rect.hint": "Drag to draw a rectangle; hold Shift for a square.",
  "draw.tool.ellipse": "Ellipse",
  "draw.tool.ellipse.hint": "Drag to draw an ellipse; hold Shift for a circle.",
  "draw.tool.line": "Line",
  "draw.tool.line.hint": "Drag to draw a line; hold Shift to snap the angle to 15° steps.",
  "draw.tool.arrow": "Arrow",
  "draw.tool.arrow.hint": "Drag to draw an arrow; hold Shift to snap the angle to 15° steps.",
  "draw.color.black": "Black",
  "draw.color.blue": "Blue",
  "draw.color.vermilion": "Vermilion",
  "draw.color.green": "Green",
  "draw.color.purple": "Purple",
  "draw.color.orange": "Orange",
  "draw.color.sky": "Sky blue",
  "draw.color.yellow": "Yellow",
  "draw.color.custom": "Custom {code}",
  "draw.color.custom.light": "Custom {code}, light: hard to read on white paper",
  "draw.color.more": "Other color…",
  "draw.color.dialog": "Custom color",
  "draw.color.code": "Color code",
  "draw.width.thin": "Thin",
  "draw.width.medium": "Medium",
  "draw.width.thick": "Thick",
  "draw.undo": "Undo",
  "draw.redo": "Redo",
  "draw.delete": "Delete selection",
  "draw.zoom_in": "Zoom in",
  "draw.zoom_out": "Zoom out",
  "draw.zoom_reset": "{zoom}: reset zoom to 100%",
  "draw.fit": "Show the whole drawing",
  "draw.title": "What did you draw?",
  "draw.title.placeholder": "For example: the home network",
  "draw.objects.one": "The drawing has {count} object.",
  "draw.objects.other": "The drawing has {count} objects.",
  "draw.selected.none": "Nothing selected.",
  "draw.selected.one": "{count} object selected.",
  "draw.selected.other": "{count} objects selected.",
  "draw.deleted.one": "{count} object deleted.",
  "draw.deleted.other": "{count} objects deleted.",
  "draw.erased.one": "{count} object erased.",
  "draw.erased.other": "{count} objects erased.",
  "draw.moved.one": "{count} object moved.",
  "draw.moved.other": "{count} objects moved.",
  "draw.added.stroke": "Stroke added.",
  "draw.added.highlight": "Highlight added.",
  "draw.added.rect": "Rectangle added.",
  "draw.added.ellipse": "Ellipse added.",
  "draw.added.line": "Line added.",
  "draw.added.arrow": "Arrow added.",
  "draw.announce.tool": "Tool: {tool}.",
  "draw.announce.color": "Color: {color}.",
  "draw.rejected": "Change not applied: {reason}.",
  "draw.reason.missing_target": "the object is gone",
  "draw.reason.missing_parent": "the layer is gone",
  "draw.reason.duplicate_id": "an identifier is already in use",
  "draw.reason.invalid": "the change is not valid",
  "draw.reason.locked": "the object is on a locked layer",
  "draw.reason.foreign": "that part comes from another program and FubDraw leaves it as it is",
  "draw.reason.limit": "the drawing has reached its maximum size",
  "draw.reason.read_only": "the drawing is read-only",
  "draw.undone": "Undone: {action}.",
  "draw.redone": "Redone: {action}.",
  "draw.undo.failed": "Cannot undo “{action}”: the drawing has changed in the meantime.",
  "draw.redo.failed": "Cannot redo “{action}”: the drawing has changed in the meantime.",
  "draw.no_layer": "Every layer is locked or hidden: there is nowhere to draw.",
  "draw.ink_failed": "Could not save the stroke.",
  "draw.action.stroke": "Stroke",
  "draw.action.highlight": "Highlight",
  "draw.action.move": "Move",
  "draw.action.erase": "Erase",
  "draw.action.delete": "Delete",
  "draw.action.title": "Title",
  "draw.action.adopt": "Drawing made editable",
  "draw.adopted": "The drawing can now be edited.",
  "draw.kind.layer": "Layer",
  "draw.kind.group": "Group",
  "draw.kind.link": "Link",
  "draw.kind.stroke": "Stroke",
  "draw.kind.highlighter": "Highlight",
  "draw.kind.path": "Path",
  "draw.kind.circle": "Circle",
  "draw.kind.polyline": "Polyline",
  "draw.kind.polygon": "Polygon",
  "draw.kind.text": "Text",
  "draw.kind.image": "Image",
  "draw.describe.named": "{kind} “{name}”",
  "draw.describe.link": "{link} to “{note}”",
  "draw.describe.parts.one": "{count} object",
  "draw.describe.parts.other": "{count} objects",
  "draw.state.locked": "locked",
  "draw.state.hidden": "hidden",
  "draw.objects": "Objects",
  "draw.objects.empty": "The drawing is empty.",
  "draw.surface.hint": "Arrow keys move the cursor or the selection; Space presses and releases; Tab goes to the next object; Enter opens properties; ? lists the keys.",
  "draw.properties": "Properties",
  "draw.properties.selection": "Position and size",
  "draw.properties.document": "Drawing properties",
  "draw.field.width": "Width",
  "draw.field.height": "Height",
  "draw.field.title": "Title",
  "draw.field.desc": "Description",
  "draw.field.page_width": "Page width",
  "draw.field.page_height": "Page height",
  "draw.keys": "Drawing keys",
  "draw.keys.tools": "Tools",
  "draw.keys.cursor": "Drawing with the keyboard",
  "draw.keys.cursor.move": "Move the cursor: 10 px, 50 with Shift, 1 with Ctrl or ⌘",
  "draw.keys.cursor.press": "Press, then release",
  "draw.keys.cancel": "Cancel the gesture",
  "draw.keys.nudge": "Move the selection by 1, with Shift by 10",
  "draw.keys.resize": "Resize the selection by 1, with Shift by 10",
  "draw.keys.walk": "Next or previous object",
  "draw.keys.ends": "First or last object",
  "draw.keys.all": "Select all",
  "draw.keys.deselect": "Clear the selection",
  "draw.keys.actual": "Zoom to 100%",
  "draw.cursor.at": "x {x}, y {y}",
  "draw.cursor.down": "Pressed: arrows trace, Space releases, Esc cancels.",
  "draw.cursor.up": "Released.",
  "draw.resized": "Size: {width} × {height}.",
  "draw.walk": "{object}, {index} of {count}.",
  "draw.action.resize": "Resize",
  "draw.keys.paste": "Paste an image",
  "draw.action.image": "Image",
  "draw.added.image.one": "Image added.",
  "draw.added.image.other": "{count} images added.",
  "draw.image.heavy.one": "Image too large",
  "draw.image.heavy.other": "Images too large",
  "draw.image.large": "The image is {size}, and an image in a drawing can be at most {limit}. Reduce it? It will have fewer pixels, but the same size on the sheet.",
  "draw.image.shared": "The images are {size} in all, and images added together can be at most {limit}. Reduce them? They will have fewer pixels, but the same size on the sheet.",
  "draw.image.room": "The drawing has room for {limit} of images, and {size} are needed. Reduce? The images will have fewer pixels, but the same size on the sheet.",
  "draw.image.reduce": "Reduce",
  "draw.image.reducing": "Reducing the image…",
  "draw.image.unreadable": "This is not an image the drawing can read.",
  "draw.image.full": "The drawing is close to its {limit} limit: another image does not fit.",
  "draw.image.failed": "Could not reduce the image.",
  "draw.arrange": "Arrange",
  "draw.duplicate": "Duplicate",
  "draw.group": "Group",
  "draw.ungroup": "Ungroup",
  "draw.order": "Order",
  "draw.order.front": "Bring to front",
  "draw.order.forward": "Bring forward",
  "draw.order.backward": "Send backward",
  "draw.order.back": "Send to back",
  "draw.align": "Align and distribute",
  "draw.align.left": "Align left",
  "draw.align.center": "Align center",
  "draw.align.right": "Align right",
  "draw.align.top": "Align top",
  "draw.align.middle": "Align middle",
  "draw.align.bottom": "Align bottom",
  "draw.align.to_page": "{action}, relative to the page",
  "draw.distribute.x": "Distribute horizontally",
  "draw.distribute.y": "Distribute vertically",
  "draw.distribute.few": "Needs at least three objects.",
  "draw.action.duplicate": "Duplicate",
  "draw.action.order": "Reorder",
  "draw.action.group": "Group",
  "draw.action.ungroup": "Ungroup",
  "draw.action.align": "Align",
  "draw.action.distribute": "Distribute",
  "draw.duplicated.one": "{count} object duplicated.",
  "draw.duplicated.other": "{count} objects duplicated.",
  "draw.duplicate.foreign": "Not duplicated: an object has parts from another program that FubDraw cannot copy.",
  "draw.ordered.front": "Brought to front.",
  "draw.ordered.forward": "Brought forward.",
  "draw.ordered.backward": "Sent backward.",
  "draw.ordered.back": "Sent to back.",
  "draw.grouped": "Grouped {count} objects.",
  "draw.group.few": "A group needs at least two objects.",
  "draw.ungrouped.one": "{count} group ungrouped.",
  "draw.ungrouped.other": "{count} groups ungrouped.",
  "draw.ungroup.none": "None of the selected objects is a group.",
  "draw.ungroup.foreign": "Not ungrouped: the group has parts from another program that would not follow its position or style.",
  "draw.aligned.one": "{count} object aligned.",
  "draw.aligned.other": "{count} objects aligned.",
  "draw.distributed": "{count} objects distributed.",
  "draw.unchanged": "Already like that: nothing to change.",
  "draw.keys.arrange": "Go to the selection bar",
  "draw.surface.hint.arrange": "Arrow keys move the cursor or the selection; Space presses and releases; Tab goes to the next object; Enter opens properties; with a selection, Alt+F10 goes to the commands that arrange it; ? lists the keys.",
  "draw.layers": "Layers",
  "draw.layers.current": "Layers: drawing in “{name}”",
  "draw.layers.none": "Layers: the drawing has none",
  "draw.layers.none.short": "No layers",
  "draw.layer.default": "Layer {n}",
  "draw.layer.unnamed": "Unnamed layer",
  "draw.layer.new": "New layer",
  "draw.layer.rename": "Rename “{name}”…",
  "draw.layer.hide": "Hide “{name}”",
  "draw.layer.show": "Show “{name}”",
  "draw.layer.lock": "Lock “{name}”",
  "draw.layer.unlock": "Unlock “{name}”",
  "draw.layer.up": "Move “{name}” up",
  "draw.layer.down": "Move “{name}” down",
  "draw.layer.delete": "Delete “{name}”",
  "draw.layer.delete.last": "It is the only layer.",
  "draw.layer.delete.locked": "It is locked: unlock it to delete it.",
  "draw.layer.rename.dialog": "Rename layer",
  "draw.layer.name": "Layer name",
  "draw.layer.chosen": "Drawing in “{name}”.",
  "draw.layer.locked_here": "“{name}” is locked: unlock it, or choose another layer, to draw.",
  "draw.layer.hidden_here": "“{name}” is hidden: show it, or choose another layer, to draw.",
  "draw.layer.flat": "“{name}” has a transform that flattens it: you cannot draw in it.",
  "draw.layer.added": "Layer “{name}” created: drawing there.",
  "draw.layer.renamed": "The layer is now called “{name}”.",
  "draw.layer.hidden": "“{name}” hidden.",
  "draw.layer.shown": "“{name}” visible again.",
  "draw.layer.locked": "“{name}” locked.",
  "draw.layer.unlocked": "“{name}” unlocked.",
  "draw.layer.moved_up": "“{name}” is now above “{other}”.",
  "draw.layer.moved_down": "“{name}” is now below “{other}”.",
  "draw.layer.deleted": "“{name}” deleted.",
  "draw.layer.deleted.one": "“{name}” deleted, with {count} object.",
  "draw.layer.deleted.other": "“{name}” deleted, with {count} objects.",
  "draw.action.layer_add": "New layer",
  "draw.action.layer_rename": "Layer name",
  "draw.action.layer_hide": "Hide layer",
  "draw.action.layer_show": "Show layer",
  "draw.action.layer_lock": "Lock layer",
  "draw.action.layer_unlock": "Unlock layer",
  "draw.action.layer_order": "Layer order",
  "draw.action.layer_delete": "Delete layer",
  "draw.action.into_layer": "Move to layer",
  "draw.into_layer": "Move to layer",
  "draw.into_layer.here": "The selected objects are already here.",
  "draw.moved_to_layer.one": "{count} object moved to “{name}”.",
  "draw.moved_to_layer.other": "{count} objects moved to “{name}”.",
  "draw.state.current": "current",
  "draw.page_grid": "Page and grid",
  "draw.grid.show": "Show grid",
  "draw.grid.snap": "Snap to grid",
  "draw.grid.snap.free": "Hold {key} while dragging to place freely.",
  "draw.grid.step": "Spacing {step}",
  "draw.grid.shown": "Grid shown.",
  "draw.grid.hidden": "Grid hidden.",
  "draw.grid.snap.on": "Snap to grid on.",
  "draw.grid.snap.off": "Snap to grid off.",
  "draw.grid.stepped": "Grid spacing: {step}.",
  "draw.page.fit": "Fit page to drawing",
  "draw.page.fit.empty": "The drawing is empty.",
  "draw.page.fit.already": "The page already fits the drawing.",
  "draw.page.fitted": "Page fitted: {width} × {height}.",
  "draw.action.fit_page": "Fit page to drawing",
  "draw.keys.grid": "Grid",
  "draw.keys.grid.show": "Show or hide the grid",
  "draw.keys.grid.snap": "Turn snap to grid on or off",
  "draw.keys.grid.free": "Held while dragging: place freely, off the grid",
  "draw.keys.cursor.move.grid": "Move the cursor to the next grid line, five lines with Shift; freely by 1 px with Ctrl or ⌘",
  "draw.keys.nudge.grid": "Move the selection to the next grid line, five lines with Shift",
  "draw.keys.resize.grid": "Resize the selection to the next grid line, five lines with Shift",
  "draw.tool.text": "Text",
  "draw.tool.text.hint": "Tap the sheet to write a text, or a text to change it. Enter starts a new line; Escape finishes.",
  "draw.sizes": "Size",
  "draw.size.small": "Small",
  "draw.size.medium": "Medium",
  "draw.size.large": "Large",
  "draw.text.new": "New text",
  "draw.text.change": "Text",
  "draw.text.hint": "Enter starts a new line; Escape, Tab or {key}+Enter finish.",
  "draw.text.edit": "Edit text",
  "draw.action.text": "Text",
  "draw.action.text_edit": "Text edit",
  "draw.added.text": "Text added.",
  "draw.text.edited": "Text changed.",
  "draw.text.none": "Select a text to edit.",
  "draw.keys.text": "Text",
  "draw.keys.text.write": "With the Text tool: write where the cursor is, or change the text there",
  "draw.keys.text.edit": "Edit the selected text",
  "draw.keys.text.newline": "Start a new line, while writing",
  "draw.keys.text.finish": "Finish the text, while writing",
  "draw.link": "Link to a note…",
  "draw.link.change": "Change link…",
  "draw.link.open": "Open “{note}”",
  "draw.unlink": "Remove link",
  "draw.action.link": "Link",
  "draw.action.relink": "Link change",
  "draw.action.unlink": "Link removal",
  "draw.linked": "Linked to “{note}”.",
  "draw.relinked": "The link now goes to “{note}”.",
  "draw.unlinked.one": "{count} link removed.",
  "draw.unlinked.other": "{count} links removed.",
  "draw.unlink.none": "None of the selected objects is a link.",
  "draw.unlink.foreign": "Not removed: the link has parts from another program that would not follow its position or style.",
  "draw.link.nested": "Not linked: a selected object already is a link, and a link cannot hold another. Remove it first, or select it alone to change it.",
  "draw.link.open.none": "Select a link to open its note.",
  "draw.keys.link": "Link to a note, or change the selected link",
  "draw.keys.link.open": "Open the note of the selected link",
  "draw.level.essential": "Essential",
  "draw.level.standard": "Standard",
  "draw.level.expert": "Expert",
  "draw.keys.from_level": "{group} · from the {level} level",
  "draw.keys.more": "The current level is “{level}”. The keys below work from a higher level, chosen in Settings, in the “Drawings” group.",
  "draw.attributes": "Attributes",
  "draw.attributes.subject": "{object}, {tag} element",
  "draw.attributes.none": "Select an object to see its attributes.",
  "draw.attributes.many": "{count} objects are selected: select one to see its attributes.",
  "draw.attributes.name": "Attribute",
  "draw.attributes.value": "Value",
  "draw.attributes.actions": "Remove",
  "draw.attributes.id.none": "no id",
  "draw.attributes.remove": "Remove {key}",
  "draw.attributes.add.title": "Add an attribute",
  "draw.attributes.add.key": "Attribute name",
  "draw.attributes.add.value": "Value of {key}",
  "draw.attributes.add": "Add",
  "draw.attributes.added": "{key} added.",
  "draw.attributes.changed": "{key} changed.",
  "draw.attributes.removed": "{key} removed.",
  "draw.attributes.renamed": "The id is now “{id}”.",
  "draw.attributes.size": "The value is {size} characters long: the first {shown} are shown here.",
  "draw.attributes.note.ink": "It comes from the stroke’s ink: redraw the stroke to change it.",
  "draw.attributes.note.arrow": "It comes from the arrow’s geometry: move its ends to change it.",
  "draw.attributes.note.fubdraw": "FubDraw writes it.",
  "draw.attributes.note.link": "Change it with “Change link…”.",
  "draw.attributes.note.image": "It says where the image comes from, and is read-only here.",
  "draw.attributes.note.namespace": "It belongs to another program: FubDraw keeps it as it is.",
  "draw.attributes.note.long": "It is too long to change here.",
  "draw.attributes.problem.empty": "Enter a value, or remove the attribute.",
  "draw.attributes.problem.paint": "Enter a color such as #0072b2, or none.",
  "draw.attributes.problem.length": "Enter a number, such as 12 or -4.5.",
  "draw.attributes.problem.size": "Enter a non-negative number, such as 12 or 0.5.",
  "draw.attributes.problem.opacity": "Enter a number from 0 to 1, such as 0.5.",
  "draw.attributes.problem.dashes": "Enter none, or lengths separated by spaces, such as 4 2.",
  "draw.attributes.problem.keyword": "Choose one of the listed values.",
  "draw.attributes.problem.family": "Choose one of the listed fonts.",
  "draw.attributes.problem.transform": "Enter an SVG transform, such as translate(10 20) or rotate(45).",
  "draw.attributes.problem.points": "Enter pairs of numbers, such as 0,0 10,0 10,10.",
  "draw.attributes.problem.path": "Enter an SVG path, such as M0 0 L10 10.",
  "draw.attributes.problem.aspect": "Enter an alignment such as xMidYMid, followed if needed by meet or slice.",
  "draw.attributes.problem.identity": "That transform changes nothing: there is nothing to add.",
  "draw.attributes.id.empty": "An id cannot be empty.",
  "draw.attributes.id.long": "An id has at most {max} characters.",
  "draw.attributes.id.form": "An id starts with a letter or _, followed by letters, digits, _, . and -.",
  "draw.attributes.id.reserved": "Ids starting with fub- belong to FubDraw.",
  "draw.attributes.id.taken": "“{id}” is already the id of another element.",
  "draw.attributes.id.cited": "A part from another program refers to “{id}”: changing it would break the reference.",
  "draw.action.attribute": "Attribute change",
  "draw.action.rename": "Id change",
  "draw.keys.attributes.toggle": "Show or hide the attributes of the selected object",
  "draw.keys.attributes.apply": "Apply the value",
  "draw.keys.attributes.newline": "New line, in points and paths",
  "draw.keys.attributes.revert": "Restore the value; again, back to the drawing sheet",
  "draw.outline": "Outline",
  "draw.outline.solid": "Solid",
  "draw.outline.dashed": "Dashed",
  "draw.outline.dotted": "Dotted",
  "draw.outline.dashdot": "Dash-dot",
  "draw.outline.custom": "Custom: {value}",
  "draw.outline.butt": "Flat ends",
  "draw.outline.round_cap": "Round ends",
  "draw.outline.square": "Square ends",
  "draw.outline.miter": "Sharp corners",
  "draw.outline.round_join": "Round corners",
  "draw.outline.bevel": "Beveled corners",
  "draw.outline.none": "None of the selected objects has an outline.",
  "draw.outlined.one": "{style}: one outline.",
  "draw.outlined.other": "{style}: {count} outlines.",
  "draw.action.dash": "Dash pattern",
  "draw.action.cap": "Outline ends",
  "draw.action.join": "Outline corners"
};

/// Il catalogo del disegno: `t` e `plural` come quelli della shell, sulle
/// chiavi del disegno.
export const drawStrings = catalog(IT, { en: EN });
export const { t, plural } = drawStrings;
