// Le stringhe dell'editor dei disegni.
//
// Arrivano con la superficie del disegno, che la shell carica con un
// `import()` quando si apre un disegno (`lazy.ts`): chi non ne apre uno non le
// scarica. La lingua, la scala di ripiego, i nomi fra graffe e i plurali sono
// quelli della shell (`catalog` in `i18n/strings.ts`). Le stringhe che la
// shell mostra prima che la superficie arrivi, come gli avvisi di un file che
// non si apre, restano nel catalogo della shell.

import { catalog } from "../../i18n/strings";

/// Il catalogo italiano, che è anche la forma degli altri.
const IT = {
  "draw.toolbar": "Strumenti di disegno",
  "draw.surface": "Foglio del disegno",
  "draw.tools": "Strumento",
  "draw.colors": "Colore",
  "draw.widths": "Spessore",
  "draw.edit": "Modifica",
  "draw.view": "Vista",
  "draw.tool.select": "Selezione",
  "draw.tool.select.hint": "Tocca un oggetto per sceglierlo e trascinalo per spostarlo; trascina sul vuoto per sceglierne più d’uno con un riquadro. Con Maiusc aggiungi o togli oggetti dalla selezione; le frecce spostano di 1, con Maiusc di 10.",
  "draw.tool.pen": "Penna",
  "draw.tool.pen.hint": "Disegna a mano libera; con la penna lo spessore segue la pressione.",
  "draw.tool.highlighter": "Evidenziatore",
  "draw.tool.highlighter.hint": "Passa sopra ciò che vuoi mettere in risalto: il segno è largo, di spessore costante, e lascia vedere ciò che copre.",
  "draw.tool.eraser": "Gomma",
  "draw.tool.eraser.hint": "Toglie gli oggetti interi che attraversi.",
  "draw.tool.rect": "Rettangolo",
  "draw.tool.rect.hint": "Trascina per disegnare un rettangolo; con Maiusc un quadrato.",
  "draw.tool.ellipse": "Ellisse",
  "draw.tool.ellipse.hint": "Trascina per disegnare un’ellisse; con Maiusc un cerchio.",
  "draw.tool.line": "Linea",
  "draw.tool.line.hint": "Trascina per disegnare una linea; con Maiusc l’angolo va a passi di 15°.",
  "draw.tool.arrow": "Freccia",
  "draw.tool.arrow.hint": "Trascina per disegnare una freccia; con Maiusc l’angolo va a passi di 15°.",
  "draw.color.black": "Nero",
  "draw.color.blue": "Blu",
  "draw.color.vermilion": "Vermiglio",
  "draw.color.green": "Verde",
  "draw.color.purple": "Porpora",
  "draw.color.orange": "Arancione",
  "draw.color.sky": "Azzurro",
  "draw.color.yellow": "Giallo",
  "draw.color.custom": "Personalizzato {code}",
  "draw.color.custom.light": "Personalizzato {code}, chiaro: sulla carta bianca si legge poco",
  "draw.color.more": "Altro colore…",
  "draw.color.dialog": "Colore personalizzato",
  "draw.color.code": "Codice del colore",
  "draw.width.thin": "Sottile",
  "draw.width.medium": "Medio",
  "draw.width.thick": "Spesso",
  "draw.undo": "Annulla",
  "draw.redo": "Ripeti",
  "draw.delete": "Elimina la selezione",
  "draw.zoom_in": "Ingrandisci",
  "draw.zoom_out": "Riduci",
  "draw.zoom_reset": "{zoom}: riporta lo zoom al 100%",
  "draw.fit": "Mostra tutto il disegno",
  "draw.title": "Che cosa hai disegnato?",
  "draw.title.placeholder": "Per esempio: la rete di casa",
  "draw.objects.one": "Il disegno ha {count} oggetto.",
  "draw.objects.other": "Il disegno ha {count} oggetti.",
  "draw.selected.none": "Nessun oggetto scelto.",
  "draw.selected.one": "{count} oggetto scelto.",
  "draw.selected.other": "{count} oggetti scelti.",
  "draw.deleted.one": "{count} oggetto eliminato.",
  "draw.deleted.other": "{count} oggetti eliminati.",
  "draw.erased.one": "{count} oggetto cancellato.",
  "draw.erased.other": "{count} oggetti cancellati.",
  "draw.moved.one": "{count} oggetto spostato.",
  "draw.moved.other": "{count} oggetti spostati.",
  "draw.added.stroke": "Tratto aggiunto.",
  "draw.added.highlight": "Evidenziatura aggiunta.",
  "draw.added.rect": "Rettangolo aggiunto.",
  "draw.added.ellipse": "Ellisse aggiunta.",
  "draw.added.line": "Linea aggiunta.",
  "draw.added.arrow": "Freccia aggiunta.",
  "draw.announce.tool": "Strumento: {tool}.",
  "draw.announce.color": "Colore: {color}.",
  "draw.rejected": "Modifica non applicata: {reason}.",
  "draw.reason.missing_target": "l’oggetto non c’è più",
  "draw.reason.missing_parent": "il livello non c’è più",
  "draw.reason.duplicate_id": "un identificativo è già in uso",
  "draw.reason.invalid": "la modifica non è valida",
  "draw.reason.locked": "l’oggetto sta in un livello o in un gruppo bloccato",
  "draw.reason.foreign": "la parte viene da un altro programma e FubDraw la lascia com’è",
  "draw.reason.limit": "il disegno ha raggiunto la dimensione massima",
  "draw.reason.read_only": "il disegno è in sola lettura",
  "draw.undone": "Annullato: {action}.",
  "draw.redone": "Ripetuto: {action}.",
  "draw.undo.failed": "Impossibile annullare «{action}»: il disegno è cambiato nel frattempo.",
  "draw.redo.failed": "Impossibile ripetere «{action}»: il disegno è cambiato nel frattempo.",
  "draw.no_layer": "Ogni livello è bloccato o nascosto: non c’è dove disegnare.",
  "draw.ink_failed": "Impossibile salvare il tratto.",
  "draw.action.stroke": "Tratto",
  "draw.action.highlight": "Evidenziatura",
  "draw.action.move": "Spostamento",
  "draw.action.erase": "Cancellazione",
  "draw.action.delete": "Eliminazione",
  "draw.action.title": "Titolo",
  "draw.action.adopt": "Disegno reso modificabile",
  "draw.adopted": "Ora il disegno si modifica.",
  "draw.kind.layer": "Livello",
  "draw.kind.group": "Gruppo",
  "draw.kind.link": "Collegamento",
  "draw.kind.stroke": "Tratto",
  "draw.kind.highlighter": "Evidenziatura",
  "draw.kind.path": "Tracciato",
  "draw.kind.circle": "Cerchio",
  "draw.kind.polyline": "Spezzata",
  "draw.kind.polygon": "Poligono",
  "draw.kind.text": "Testo",
  "draw.kind.image": "Immagine",
  "draw.describe.named": "{kind} «{name}»",
  "draw.describe.link": "{link} a «{note}»",
  "draw.describe.parts.one": "{count} oggetto",
  "draw.describe.parts.other": "{count} oggetti",
  "draw.state.locked": "bloccato",
  "draw.state.hidden": "nascosto",
  "draw.objects": "Oggetti",
  "draw.objects.empty": "Il disegno è vuoto.",
  "draw.surface.hint": "Le frecce muovono il cursore o la selezione; Spazio preme e rilascia; Tab passa all’oggetto dopo; Invio apre le proprietà; ? elenca i tasti.",
  "draw.properties": "Proprietà",
  "draw.properties.selection": "Posizione e misure",
  "draw.properties.document": "Proprietà del disegno",
  "draw.properties.look": "Aspetto",
  "draw.properties.text": "Testo",
  "draw.properties.arrange": "Disponi",
  "draw.properties.transform": "Trasforma",
  "draw.properties.document_section": "Documento",
  "draw.properties.align": "Allinea",
  "draw.properties.distribute": "Distribuisci",
  "draw.properties.apply": "Applica",
  "draw.properties.mixed": "Misto",
  "draw.properties.none": "Nessuno",
  "draw.properties.fill": "Riempimento",
  "draw.properties.stroke": "Contorno",
  "draw.properties.ratio": "Mantieni le proporzioni",
  "draw.properties.swatches": "{label}: campioni",
  "draw.properties.picker": "{label}: selettore del sistema",
  "draw.properties.problem.empty": "Scrivi un valore.",
  "draw.properties.problem.syntax": "Scrivi un numero o un calcolo, come 120+15.",
  "draw.properties.problem.unit": "Qui valgono queste unità: {units}.",
  "draw.properties.problem.relative": "I valori sono diversi, e una percentuale non ha di che essere parte: scrivi un numero.",
  "draw.properties.problem.finite": "Il risultato non è un numero: forse una divisione per zero.",
  "draw.properties.problem.paint": "Scrivi un colore: un codice come #0072b2, un nome come red, o «nessuno».",
  "draw.properties.problem.mixed": "I valori sono diversi: scrivi quello da dare a tutti.",
  "draw.properties.drawing": "Il disegno",
  "draw.properties.rotation": "Rotazione",
  "draw.properties.stroke_width": "Spessore",
  "draw.properties.opacity": "Opacità",
  "draw.properties.dash": "Tratteggio",
  "draw.properties.cap": "Estremi",
  "draw.properties.join": "Angoli",
  "draw.properties.family": "Carattere",
  "draw.properties.family.default": "Predefinito",
  "draw.properties.size": "Dimensione",
  "draw.properties.anchor": "Allineamento",
  "draw.properties.anchor.start": "A sinistra",
  "draw.properties.anchor.middle": "Al centro",
  "draw.properties.anchor.end": "A destra",
  "draw.properties.turn": "Rotazione oraria",
  "draw.properties.scale_x": "Scala orizzontale",
  "draw.properties.scale_y": "Scala verticale",
  "draw.properties.skew_x": "Inclinazione orizzontale",
  "draw.properties.skew_y": "Inclinazione verticale",
  "draw.properties.unit": "Unità di misura",
  "draw.properties.zero_scale": "Una scala dello zero per cento schiaccerebbe gli oggetti: scrivi un valore diverso da zero.",
  "draw.feature.properties": "Pannello delle proprietà",
  "draw.bar.beside": "Barra accanto alla selezione",
  "draw.bar.beside.on": "La barra della selezione sta accanto alla selezione.",
  "draw.bar.beside.off": "La barra della selezione sta in cima al foglio.",
  "draw.action.fill": "Riempimento",
  "draw.action.outline_color": "Colore del contorno",
  "draw.action.stroke_width": "Spessore del contorno",
  "draw.action.opacity": "Opacità",
  "draw.action.font": "Carattere",
  "draw.action.font_size": "Dimensione del testo",
  "draw.action.text_align": "Allineamento del testo",
  "draw.action.page_size": "Misure della pagina",
  "draw.action.desc": "Descrizione",
  "draw.keys.properties.panel": "Va al pannello delle proprietà",
  "draw.keys.properties.step": "In un campo numerico: aumenta o diminuisce di 1, con Maiusc di 10",
  "draw.keys.properties.apply": "Scrive il valore del campo",
  "draw.keys.properties.text": "Nella descrizione: scrive il testo",
  "draw.keys.properties.revert": "Riporta il campo a com’era; di nuovo, torna al foglio",
  "draw.keys.attributes.focus": "Va agli attributi, nel pannello delle proprietà",
  "draw.field.width": "Larghezza",
  "draw.field.height": "Altezza",
  "draw.field.title": "Titolo",
  "draw.field.desc": "Descrizione",
  "draw.field.page_width": "Larghezza della pagina",
  "draw.field.page_height": "Altezza della pagina",
  "draw.keys": "Tasti del disegno",
  "draw.keys.tools": "Strumenti",
  "draw.keys.cursor": "Disegnare da tastiera",
  "draw.keys.cursor.move": "Muove il cursore: 10 px, 50 con Maiusc, 1 con Ctrl o ⌘",
  "draw.keys.cursor.press": "Preme, e poi rilascia",
  "draw.keys.cancel": "Annulla il gesto",
  "draw.keys.nudge": "Sposta la selezione di 1, con Maiusc di 10",
  "draw.keys.resize": "Ridimensiona la selezione di 1, con Maiusc di 10",
  "draw.keys.rotate": "Ruota la selezione di 15° in senso antiorario o orario, con Maiusc di 90°",
  "draw.keys.walk": "L’oggetto dopo o prima",
  "draw.keys.ends": "Il primo o l’ultimo oggetto",
  "draw.keys.all": "Sceglie tutto",
  "draw.keys.deselect": "Toglie la selezione",
  "draw.keys.actual": "Zoom al 100%",
  "draw.cursor.at": "x {x}, y {y}",
  "draw.cursor.down": "Premuto: le frecce tracciano, Spazio rilascia, Esc annulla.",
  "draw.cursor.up": "Rilasciato.",
  "draw.resized": "Misure: {width} × {height}.",
  "draw.walk": "{object}, {index} di {count}.",
  "draw.action.resize": "Ridimensionamento",
  "draw.action.rotate": "Rotazione",
  "draw.rotated.clockwise": "Rotazione di {angle} in senso orario.",
  "draw.rotated.counter": "Rotazione di {angle} in senso antiorario.",
  "draw.keys.paste": "Incolla un’immagine",
  "draw.action.image": "Immagine",
  "draw.added.image.one": "Immagine aggiunta.",
  "draw.added.image.other": "{count} immagini aggiunte.",
  "draw.image.heavy.one": "Immagine troppo pesante",
  "draw.image.heavy.other": "Immagini troppo pesanti",
  "draw.image.large": "L’immagine pesa {size}, e in un disegno un’immagine può pesare al più {limit}. Ridurla? Avrà meno pixel, ma la stessa misura sul foglio.",
  "draw.image.shared": "Le immagini pesano {size} in tutto, e quelle aggiunte insieme possono pesare al più {limit}. Ridurle? Avranno meno pixel, ma la stessa misura sul foglio.",
  "draw.image.room": "Nel disegno resta posto per {limit} di immagini, e ne servono {size}. Ridurre? Le immagini avranno meno pixel, ma la stessa misura sul foglio.",
  "draw.image.reduce": "Riduci",
  "draw.image.reducing": "Riduzione dell’immagine…",
  "draw.image.unreadable": "Non è un’immagine che il disegno sa leggere.",
  "draw.image.full": "Il disegno è vicino al limite di {limit}: un’altra immagine non ci sta.",
  "draw.image.failed": "Impossibile ridurre l’immagine.",
  "draw.insert": "Inserisci",
  "draw.image.vault": "Immagine dal vault…",
  "draw.image.gone": "L’immagine scelta non si apre: forse non è più nel vault.",
  "draw.arrange": "Disponi",
  "draw.duplicate": "Duplica",
  "draw.group": "Raggruppa",
  "draw.ungroup": "Separa",
  "draw.order": "Ordine",
  "draw.order.front": "Porta in primo piano",
  "draw.order.forward": "Porta avanti",
  "draw.order.backward": "Porta indietro",
  "draw.order.back": "Porta in secondo piano",
  "draw.align": "Allinea e distribuisci",
  "draw.align.left": "Allinea a sinistra",
  "draw.align.center": "Allinea al centro",
  "draw.align.right": "Allinea a destra",
  "draw.align.top": "Allinea in alto",
  "draw.align.middle": "Allinea in mezzo",
  "draw.align.bottom": "Allinea in basso",
  "draw.align.to_page": "{action}, rispetto alla pagina",
  "draw.distribute.x": "Distribuisci orizzontalmente",
  "draw.distribute.y": "Distribuisci verticalmente",
  "draw.distribute.few": "Servono almeno tre oggetti.",
  "draw.action.duplicate": "Duplicazione",
  "draw.action.order": "Cambio d’ordine",
  "draw.action.group": "Raggruppamento",
  "draw.action.ungroup": "Separazione",
  "draw.action.align": "Allineamento",
  "draw.action.distribute": "Distribuzione",
  "draw.duplicated.one": "{count} oggetto duplicato.",
  "draw.duplicated.other": "{count} oggetti duplicati.",
  "draw.duplicate.foreign": "Non duplicato: un oggetto ha parti di un altro programma, che FubDraw non sa copiare.",
  "draw.ordered.front": "In primo piano.",
  "draw.ordered.forward": "Un posto più avanti.",
  "draw.ordered.backward": "Un posto più indietro.",
  "draw.ordered.back": "In secondo piano.",
  "draw.grouped": "Gruppo di {count} oggetti.",
  "draw.group.few": "Per un gruppo servono almeno due oggetti.",
  "draw.ungrouped.one": "{count} gruppo separato.",
  "draw.ungrouped.other": "{count} gruppi separati.",
  "draw.ungroup.none": "Fra gli oggetti scelti non c’è un gruppo.",
  "draw.ungroup.foreign": "Non separato: il gruppo ha parti di un altro programma, che non seguirebbero la sua posizione o il suo stile.",
  "draw.aligned.one": "{count} oggetto allineato.",
  "draw.aligned.other": "{count} oggetti allineati.",
  "draw.distributed": "{count} oggetti distribuiti.",
  "draw.unchanged": "È già così: niente da cambiare.",
  "draw.keys.arrange": "Va alla barra della selezione",
  "draw.surface.hint.arrange": "Le frecce muovono il cursore o la selezione; Spazio preme e rilascia; Tab passa all’oggetto dopo; Invio apre le proprietà; con una selezione, Alt+F10 porta ai comandi per disporla; ? elenca i tasti.",
  "draw.layers": "Livelli",
  "draw.layers.current": "Livelli: si disegna in «{name}»",
  "draw.layers.none": "Livelli: il disegno non ne ha",
  "draw.layers.none.short": "Nessun livello",
  "draw.layer.default": "Livello {n}",
  "draw.layer.unnamed": "Livello senza nome",
  "draw.layer.new": "Nuovo livello",
  "draw.layer.rename": "Rinomina «{name}»…",
  "draw.layer.hide": "Nascondi «{name}»",
  "draw.layer.show": "Mostra «{name}»",
  "draw.layer.lock": "Blocca «{name}»",
  "draw.layer.unlock": "Sblocca «{name}»",
  "draw.layer.up": "Sposta «{name}» su",
  "draw.layer.down": "Sposta «{name}» giù",
  "draw.layer.delete": "Elimina «{name}»",
  "draw.layer.delete.last": "È l’unico livello.",
  "draw.layer.delete.locked": "È bloccato: sbloccalo per eliminarlo.",
  "draw.layer.rename.dialog": "Rinomina il livello",
  "draw.layer.name": "Nome del livello",
  "draw.layer.chosen": "Si disegna in «{name}».",
  "draw.layer.locked_here": "«{name}» è bloccato: sbloccalo, o scegli un altro livello, per disegnare.",
  "draw.layer.hidden_here": "«{name}» è nascosto: mostralo, o scegli un altro livello, per disegnare.",
  "draw.layer.flat": "«{name}» ha una trasformazione che lo schiaccia: non ci si disegna.",
  "draw.layer.added": "Livello «{name}» creato: si disegna lì.",
  "draw.layer.renamed": "Il livello ora si chiama «{name}».",
  "draw.layer.hidden": "«{name}» nascosto.",
  "draw.layer.shown": "«{name}» di nuovo visibile.",
  "draw.layer.locked": "«{name}» bloccato.",
  "draw.layer.unlocked": "«{name}» sbloccato.",
  "draw.layer.moved_up": "«{name}» ora sta sopra «{other}».",
  "draw.layer.moved_down": "«{name}» ora sta sotto «{other}».",
  "draw.layer.deleted": "«{name}» eliminato.",
  "draw.layer.deleted.one": "«{name}» eliminato, con {count} oggetto.",
  "draw.layer.deleted.other": "«{name}» eliminato, con {count} oggetti.",
  "draw.action.layer_add": "Nuovo livello",
  "draw.action.layer_rename": "Nome del livello",
  "draw.action.layer_hide": "Livello nascosto",
  "draw.action.layer_show": "Livello mostrato",
  "draw.action.layer_lock": "Livello bloccato",
  "draw.action.layer_unlock": "Livello sbloccato",
  "draw.action.layer_order": "Ordine dei livelli",
  "draw.action.layer_delete": "Eliminazione del livello",
  "draw.action.into_layer": "Spostamento in un livello",
  "draw.into_layer": "Sposta in un livello",
  "draw.into_layer.here": "Gli oggetti scelti sono già qui.",
  "draw.moved_to_layer.one": "{count} oggetto spostato in «{name}».",
  "draw.moved_to_layer.other": "{count} oggetti spostati in «{name}».",
  "draw.state.current": "corrente",
  "draw.page_grid": "Pagina e griglia",
  "draw.grid.show": "Mostra la griglia",
  "draw.grid.snap": "Aggancia alla griglia",
  "draw.grid.snap.free": "Tieni premuto {key} mentre trascini per posare libero.",
  "draw.grid.step": "Passo di {step}",
  "draw.grid.shown": "Griglia visibile.",
  "draw.grid.hidden": "Griglia nascosta.",
  "draw.grid.snap.on": "Aggancio alla griglia acceso.",
  "draw.grid.snap.off": "Aggancio alla griglia spento.",
  "draw.grid.stepped": "Passo della griglia: {step}.",
  "draw.guides.hint": "Allinea ai bordi e ai centri degli altri oggetti e della pagina. Tieni premuto {key} mentre trascini per posare libero.",
  "draw.guides.on": "Guide intelligenti accese.",
  "draw.guides.off": "Guide intelligenti spente.",
  "draw.guides.snapped": "Agganciato: {parts}.",
  "draw.guides.object": "{source} in linea con {edge} di {name}",
  "draw.guides.object.same": "{source} in linea con quello di {name}",
  "draw.guides.page": "{source} in linea con {edge} della pagina",
  "draw.guides.page.same": "{source} in linea con quello della pagina",
  "draw.guides.node": "{source} in linea con un nodo",
  "draw.guides.spaced.x": "a distanze uguali in orizzontale, {gap}",
  "draw.guides.spaced.y": "a distanze uguali in verticale, {gap}",
  "draw.guides.edge.left": "il bordo sinistro",
  "draw.guides.edge.center_x": "il centro orizzontale",
  "draw.guides.edge.right": "il bordo destro",
  "draw.guides.edge.top": "il bordo superiore",
  "draw.guides.edge.center_y": "il centro verticale",
  "draw.guides.edge.bottom": "il bordo inferiore",
  "draw.guides.edge.point": "il punto",
  "draw.page.fit": "Adatta la pagina al disegno",
  "draw.page.fit.empty": "Il disegno è vuoto.",
  "draw.page.fit.already": "La pagina è già adattata al disegno.",
  "draw.page.fitted": "Pagina adattata: {width} × {height}.",
  "draw.action.fit_page": "Pagina adattata al disegno",
  "draw.keys.grid": "Griglia",
  "draw.keys.grid.show": "Mostra o nasconde la griglia",
  "draw.keys.grid.snap": "Accende o spegne l’aggancio alla griglia",
  "draw.keys.grid.free": "Tenuto mentre si trascina: posa libero, fuori dalla griglia",
  "draw.keys.guides": "Guide intelligenti",
  "draw.keys.guides.free": "Tenuto mentre si trascina: posa libero, senza agganciarsi agli altri oggetti",
  "draw.keys.guides.measure": "Tenuto con una selezione: le distanze dall’oggetto sotto il puntatore, o dalla pagina",
  "draw.keys.cursor.move.grid": "Muove il cursore alla riga seguente della griglia, a cinque righe con Maiusc; libero di 1 px con Ctrl o ⌘",
  "draw.keys.nudge.grid": "Sposta la selezione alla riga seguente della griglia, a cinque righe con Maiusc",
  "draw.keys.resize.grid": "Ridimensiona la selezione fino alla riga seguente della griglia, a cinque righe con Maiusc",
  "draw.rulers.show": "Mostra i righelli",
  "draw.rulers.hide": "Nascondi i righelli",
  "draw.rulers.shown": "Righelli visibili.",
  "draw.rulers.hidden": "Righelli nascosti.",
  "draw.rulers.guides.show": "Mostra le guide",
  "draw.rulers.guides.hint": "Le guide tirate dai righelli: ciò che si muove ci si aggancia, finché si vedono.",
  "draw.rulers.guides.shown": "Guide visibili.",
  "draw.rulers.guides.hidden": "Guide nascoste.",
  "draw.units.item": "Unità: {unit}…",
  "draw.unit.px": "Pixel",
  "draw.unit.mm": "Millimetri",
  "draw.unit.cm": "Centimetri",
  "draw.unit.in": "Pollici",
  "draw.unit.pt": "Punti",
  "draw.unit.pt.one": "{value} punto",
  "draw.unit.pt.other": "{value} punti",
  "draw.units.now.px": "Il documento ora misura in pixel.",
  "draw.units.now.mm": "Il documento ora misura in millimetri.",
  "draw.units.now.cm": "Il documento ora misura in centimetri.",
  "draw.units.now.in": "Il documento ora misura in pollici.",
  "draw.units.now.pt": "Il documento ora misura in punti.",
  "draw.units.hint": "Righelli, campi e misure. Il disegno non cambia.",
  "draw.action.units": "Unità del documento",
  "draw.action.guide_add": "Nuova guida",
  "draw.action.guide_move": "Spostamento di una guida",
  "draw.action.guide_delete": "Eliminazione di una guida",
  "draw.action.guide_lock": "Guida bloccata",
  "draw.action.guide_unlock": "Guida sbloccata",
  "draw.action.guides": "Guide",
  "draw.guide.added.x": "Guida verticale aggiunta a {at}.",
  "draw.guide.added.y": "Guida orizzontale aggiunta a {at}.",
  "draw.guide.moved.x": "Guida verticale spostata a {at}.",
  "draw.guide.moved.y": "Guida orizzontale spostata a {at}.",
  "draw.guide.deleted.x": "Guida verticale eliminata.",
  "draw.guide.deleted.y": "Guida orizzontale eliminata.",
  "draw.guide.locked": "Guida bloccata.",
  "draw.guide.unlocked": "Guida sbloccata.",
  "draw.guide.drop": "Rilascia per eliminare",
  "draw.guide.lock": "Blocca la guida",
  "draw.guide.unlock": "Sblocca la guida",
  "draw.guide.delete": "Elimina la guida",
  "draw.guides.line": "{source} in linea con una guida",
  "draw.guides.lock_all": "Blocca tutte le guide",
  "draw.guides.unlock_all": "Sblocca tutte le guide",
  "draw.guides.delete_all": "Elimina tutte le guide",
  "draw.guides.all_locked": "Guide bloccate.",
  "draw.guides.all_unlocked": "Guide sbloccate.",
  "draw.guides.deleted.one": "{count} guida eliminata.",
  "draw.guides.deleted.other": "{count} guide eliminate.",
  "draw.guides.changed": "Guide aggiornate.",
  "draw.guides.full": "Il documento ha già {count} guide, quante ne può avere.",
  "draw.guides.unreadable": "Le guide scritte nel file non si leggono: restano com’erano finché non le riscrivi qui.",
  "draw.guides.dialog": "Guide…",
  "draw.guides.dialog.title": "Guide",
  "draw.guides.dialog.empty": "Il documento non ha guide. Aggiungine una qui, o tirala da un righello.",
  "draw.guides.dialog.hint": "Le posizioni partono dallo zero dei righelli: le verticali verso destra, le orizzontali verso il basso.",
  "draw.guides.column.axis": "Direzione",
  "draw.guides.column.position": "Posizione",
  "draw.guides.axis_label": "Direzione della guida {index}",
  "draw.guides.vertical": "Verticale",
  "draw.guides.horizontal": "Orizzontale",
  "draw.guides.position": "Posizione della guida {index}, {axis}",
  "draw.guides.locked_field": "Bloccata",
  "draw.guides.locked_label": "Guida {index}, {axis}: bloccata",
  "draw.guides.delete_label": "Elimina la guida {index}, {axis}",
  "draw.guides.add_x": "Aggiungi una verticale",
  "draw.guides.add_y": "Aggiungi un’orizzontale",
  "draw.guides.invalid": "Scrivi la posizione della guida {index} come numero.",
  "draw.keys.rulers": "Righelli e guide",
  "draw.keys.rulers.show": "Mostra o nasconde i righelli",
  "draw.keys.rulers.guides": "Mostra o nasconde le guide",
  "draw.keys.rulers.free": "Tenuto mentre si tira una guida: posa libero, senza agganciarsi",
  "draw.tool.text": "Testo",
  "draw.tool.text.hint": "Tocca il foglio per scrivere un testo, o un testo per cambiarlo. Invio va a capo; Esc conclude.",
  "draw.sizes": "Dimensione",
  "draw.size.small": "Piccolo",
  "draw.size.medium": "Medio",
  "draw.size.large": "Grande",
  "draw.text.new": "Testo nuovo",
  "draw.text.change": "Testo",
  "draw.text.hint": "Invio va a capo; Esc, Tab o {key}+Invio concludono.",
  "draw.text.edit": "Modifica il testo",
  "draw.action.text": "Testo",
  "draw.action.text_edit": "Modifica del testo",
  "draw.added.text": "Testo aggiunto.",
  "draw.text.edited": "Testo modificato.",
  "draw.text.none": "Scegli un testo da modificare.",
  "draw.keys.text": "Testo",
  "draw.keys.text.write": "Con lo strumento Testo: scrive dov’è il cursore, o cambia il testo che c’è",
  "draw.keys.text.edit": "Modifica il testo scelto",
  "draw.keys.text.newline": "Va a capo, mentre si scrive",
  "draw.keys.text.finish": "Conclude il testo, mentre si scrive",
  "draw.link": "Collega a una nota…",
  "draw.link.change": "Cambia il collegamento…",
  "draw.link.open": "Apri «{note}»",
  "draw.unlink": "Togli il collegamento",
  "draw.action.link": "Collegamento",
  "draw.action.relink": "Cambio del collegamento",
  "draw.action.unlink": "Rimozione del collegamento",
  "draw.linked": "Collegato a «{note}».",
  "draw.relinked": "Ora il collegamento porta a «{note}».",
  "draw.unlinked.one": "{count} collegamento tolto.",
  "draw.unlinked.other": "{count} collegamenti tolti.",
  "draw.unlink.none": "Fra gli oggetti scelti non c’è un collegamento.",
  "draw.unlink.foreign": "Non tolto: il collegamento ha parti di un altro programma, che non seguirebbero la sua posizione o il suo stile.",
  "draw.link.nested": "Non collegato: fra gli oggetti scelti c’è già un collegamento, e un collegamento non ne contiene un altro. Toglilo prima, o sceglilo da solo per cambiarlo.",
  "draw.link.open.none": "Scegli un collegamento per aprire la sua nota.",
  "draw.keys.link": "Collega a una nota, o cambia il collegamento scelto",
  "draw.keys.link.open": "Apre la nota del collegamento scelto",
  "draw.level.essential": "Essenziale",
  "draw.level.standard": "Standard",
  "draw.level.expert": "Esperto",
  "draw.level.custom": "Personalizzato",
  "draw.keys.from_level": "{group} · dal livello {level}",
  "draw.keys.more": "Il livello di adesso è «{level}». I tasti qui sotto valgono da un livello più alto, che si sceglie nelle Impostazioni, nel gruppo «Disegni».",
  "draw.keys.more.custom": "Il livello di adesso è «Personalizzato». I tasti qui sotto sono delle parti che non ha: si aggiungono nelle Impostazioni, nel gruppo «Disegni».",
  "draw.feature.colors": "Colori personalizzati",
  "draw.feature.arrange": "Duplica, raggruppa, ordina, allinea e distribuisci",
  "draw.feature.layers": "Livelli",
  "draw.feature.grid": "Pagina e griglia",
  "draw.feature.guides": "Guide intelligenti",
  "draw.feature.rulers": "Righelli e guide",
  "draw.feature.links": "Collegamenti alle note",
  "draw.feature.images": "Immagini dal vault",
  "draw.feature.attributes": "Attributi",
  "draw.feature.outline": "Contorno: tratteggio, estremi e angoli",
  "draw.feature.transform": "Trasforma: rotazione, scala e inclinazione",
  "draw.feature.apply": "Applica trasformazione",
  "draw.feature.path": "Oggetto in tracciato",
  "draw.feature.boolean": "Operazioni booleane",
  "draw.attributes": "Attributi",
  "draw.attributes.subject": "{object}, elemento {tag}",
  "draw.attributes.none": "Scegli un oggetto per vederne gli attributi.",
  "draw.attributes.many": "Gli oggetti scelti sono {count}: scegline uno per vederne gli attributi.",
  "draw.attributes.name": "Attributo",
  "draw.attributes.value": "Valore",
  "draw.attributes.actions": "Togli",
  "draw.attributes.id.none": "senza id",
  "draw.attributes.remove": "Togli {key}",
  "draw.attributes.add.title": "Aggiungi un attributo",
  "draw.attributes.add.key": "Nome dell’attributo",
  "draw.attributes.add.value": "Valore di {key}",
  "draw.attributes.add": "Aggiungi",
  "draw.attributes.added": "{key} aggiunto.",
  "draw.attributes.changed": "{key} cambiato.",
  "draw.attributes.removed": "{key} tolto.",
  "draw.attributes.renamed": "Ora l’id è «{id}».",
  "draw.attributes.size": "Il valore è lungo {size} caratteri: qui se ne vedono i primi {shown}.",
  "draw.attributes.note.ink": "Viene dall’inchiostro del tratto: si cambia ridisegnandolo.",
  "draw.attributes.note.arrow": "Viene dalla geometria della freccia: si cambia spostandone le estremità.",
  "draw.attributes.note.fubdraw": "Lo scrive FubDraw.",
  "draw.attributes.note.link": "Si cambia con «Cambia il collegamento…».",
  "draw.attributes.note.image": "Dice da dove viene l’immagine, e qui si legge soltanto.",
  "draw.attributes.note.namespace": "È di un altro programma: FubDraw lo conserva com’è.",
  "draw.attributes.note.long": "È troppo lungo per cambiarlo qui.",
  "draw.attributes.problem.empty": "Scrivi un valore, o togli l’attributo.",
  "draw.attributes.problem.paint": "Ci vuole un colore come #0072b2, o none.",
  "draw.attributes.problem.length": "Ci vuole un numero, come 12 o -4.5.",
  "draw.attributes.problem.size": "Ci vuole un numero non negativo, come 12 o 0.5.",
  "draw.attributes.problem.opacity": "Ci vuole un numero da 0 a 1, come 0.5.",
  "draw.attributes.problem.dashes": "Ci vuole none, o delle lunghezze separate da spazi, come 4 2.",
  "draw.attributes.problem.keyword": "Ci vuole uno dei valori della scelta.",
  "draw.attributes.problem.family": "Ci vuole uno dei caratteri della scelta.",
  "draw.attributes.problem.transform": "Ci vuole una trasformazione SVG, come translate(10 20) o rotate(45).",
  "draw.attributes.problem.points": "Ci vogliono delle coppie di numeri, come 0,0 10,0 10,10.",
  "draw.attributes.problem.path": "Ci vuole un percorso SVG, come M0 0 L10 10.",
  "draw.attributes.problem.aspect": "Ci vuole un allineamento come xMidYMid, seguito se serve da meet o slice.",
  "draw.attributes.problem.identity": "È la trasformazione che non cambia niente: non c’è niente da aggiungere.",
  "draw.attributes.id.empty": "Un id non può essere vuoto.",
  "draw.attributes.id.long": "Un id ha al più {max} caratteri.",
  "draw.attributes.id.form": "Un id comincia con una lettera o _, e continua con lettere, cifre, _, . e -.",
  "draw.attributes.id.reserved": "Gli id che cominciano con fub- sono di FubDraw.",
  "draw.attributes.id.taken": "«{id}» è già l’id di un altro elemento.",
  "draw.attributes.id.cited": "Una parte di un altro programma cita «{id}»: cambiarlo romperebbe il riferimento.",
  "draw.action.attribute": "Modifica di un attributo",
  "draw.action.rename": "Cambio dell’id",
  "draw.keys.attributes.toggle": "Mostra o nasconde gli attributi dell’oggetto scelto",
  "draw.keys.attributes.apply": "Applica il valore scritto",
  "draw.keys.attributes.newline": "Va a capo, nei punti e nei percorsi",
  "draw.keys.attributes.revert": "Riporta il valore com’era; di nuovo, torna al foglio",
  "draw.outline": "Contorno",
  "draw.outline.solid": "Continuo",
  "draw.outline.dashed": "Tratteggiato",
  "draw.outline.dotted": "Punteggiato",
  "draw.outline.dashdot": "Tratto e punto",
  "draw.outline.custom": "Su misura: {value}",
  "draw.outline.butt": "Estremi piatti",
  "draw.outline.round_cap": "Estremi arrotondati",
  "draw.outline.square": "Estremi quadrati",
  "draw.outline.miter": "Angoli vivi",
  "draw.outline.round_join": "Angoli arrotondati",
  "draw.outline.bevel": "Angoli smussati",
  "draw.outline.none": "Nessun oggetto scelto ha un contorno.",
  "draw.outlined.one": "{style}: un contorno.",
  "draw.outlined.other": "{style}: {count} contorni.",
  "draw.action.dash": "Tratteggio",
  "draw.action.cap": "Estremi del contorno",
  "draw.action.join": "Angoli del contorno",
  "draw.transform": "Trasforma…",
  "draw.transform.title": "Trasforma",
  "draw.transform.message": "Attorno al centro degli oggetti scelti: prima la scala, poi l’inclinazione, poi la rotazione. Una scala negativa rispecchia.",
  "draw.transform.rotate": "Rotazione in senso orario (°)",
  "draw.transform.scale_x": "Scala orizzontale (%)",
  "draw.transform.scale_y": "Scala verticale (%)",
  "draw.transform.skew_x": "Inclinazione orizzontale (°)",
  "draw.transform.skew_y": "Inclinazione verticale (°)",
  "draw.transform.unwritable": "Un oggetto diventerebbe troppo piccolo per scriverne la trasformazione: niente è cambiato.",
  "draw.transformed.one": "{count} oggetto trasformato.",
  "draw.transformed.other": "{count} oggetti trasformati.",
  "draw.action.transform": "Trasformazione",
  "draw.apply_transform": "Applica trasformazione",
  "draw.applied.one": "Trasformazione applicata a {count} oggetto.",
  "draw.applied.other": "Trasformazione applicata a {count} oggetti.",
  "draw.applied.kept.one": "{count} oggetto conserva una trasformazione che la sua forma non sa scrivere.",
  "draw.applied.kept.other": "{count} oggetti conservano una trasformazione che la loro forma non sa scrivere.",
  "draw.action.apply_transform": "Applicazione della trasformazione",
  "draw.to_path": "Oggetto in tracciato",
  "draw.traced.one": "{count} oggetto è diventato un tracciato.",
  "draw.traced.other": "{count} oggetti sono diventati tracciati.",
  "draw.traced.refused.one": "{count} oggetto resta com’è: testi, immagini e forme vuote non diventano tracciati.",
  "draw.traced.refused.other": "{count} oggetti restano come sono: testi, immagini e forme vuote non diventano tracciati.",
  "draw.action.to_path": "Oggetto in tracciato",
  "draw.boolean": "Operazioni booleane",
  "draw.boolean.union": "Unione",
  "draw.boolean.difference": "Differenza",
  "draw.boolean.intersection": "Intersezione",
  "draw.boolean.exclusion": "Esclusione",
  "draw.boolean.division": "Divisione",
  "draw.boolean.few": "Servono almeno due forme.",
  "draw.boolean.not_shapes.one": "Le operazioni booleane lavorano sulle forme: {count} oggetto scelto non lo è.",
  "draw.boolean.not_shapes.other": "Le operazioni booleane lavorano sulle forme: {count} oggetti scelti non lo sono.",
  "draw.boolean.empty": "Il risultato sarebbe vuoto: niente è cambiato.",
  "draw.boolean.whole": "Le altre forme non dividono quella più in basso: niente è cambiato.",
  "draw.boolean.foreign": "La forma più in basso ha attributi di un altro programma che FubDraw non sa riscrivere: niente è cambiato.",
  "draw.boolean.failed": "Il calcolo non riesce su queste forme: niente è cambiato.",
  "draw.combined.one": "{action}: {count} forma diventa un tracciato.",
  "draw.combined.other": "{action}: {count} forme diventano un tracciato.",
  "draw.divided": "Divisione: la forma diventa {count} tracciati.",
  "draw.action.union": "Unione",
  "draw.action.difference": "Differenza",
  "draw.action.intersection": "Intersezione",
  "draw.action.exclusion": "Esclusione",
  "draw.action.division": "Divisione",
  "draw.tool.nodes": "Nodi",
  "draw.tool.nodes.hint": "Modifica i nodi del tracciato scelto: trascina un nodo, una maniglia o un segmento, o sul vuoto per scegliere più nodi con un riquadro. Con Maiusc aggiungi o togli nodi; il doppio tocco su un segmento aggiunge un nodo; le frecce spostano i nodi scelti.",
  "draw.nodes.bar": "Comandi dei nodi",
  "draw.nodes.insert": "Aggiungi nodi",
  "draw.nodes.delete": "Elimina nodi",
  "draw.nodes.corner": "Nodi a spigolo",
  "draw.nodes.smooth": "Nodi lisci",
  "draw.nodes.symmetric": "Nodi simmetrici",
  "draw.nodes.line": "Segmenti in linee",
  "draw.nodes.curve": "Segmenti in curve",
  "draw.nodes.break": "Spezza ai nodi",
  "draw.nodes.join": "Unisci i capi",
  "draw.nodes.place": "Posizione dei nodi",
  "draw.nodes.walk": "Nodo {index} di {count}, {kind}: x {x}, y {y}.",
  "draw.nodes.kind.corner": "spigolo",
  "draw.nodes.kind.smooth": "liscio",
  "draw.nodes.kind.symmetric": "simmetrico",
  "draw.nodes.kind.end": "capo",
  "draw.nodes.shown.one": "{object}: {count} nodo da modificare.",
  "draw.nodes.shown.other": "{object}: {count} nodi da modificare.",
  "draw.nodes.selected.none": "Nessun nodo scelto.",
  "draw.nodes.selected.one": "{count} nodo scelto.",
  "draw.nodes.selected.other": "{count} nodi scelti.",
  "draw.nodes.no_path": "L’oggetto scelto non è un tracciato: «Oggetto in tracciato» lo rende modificabile coi nodi.",
  "draw.nodes.many": "Scegli un oggetto solo per modificarne i nodi.",
  "draw.nodes.unreadable": "I dati di questo tracciato non si leggono: i suoi nodi non si modificano.",
  "draw.nodes.flat": "Questo tracciato è schiacciato su una linea: i suoi nodi non si modificano.",
  "draw.nodes.empty": "Questo tracciato non ha nodi.",
  "draw.nodes.moved.at": "Nodo spostato: x {x}, y {y}.",
  "draw.nodes.moved.one": "{count} nodo spostato.",
  "draw.nodes.moved.other": "{count} nodi spostati.",
  "draw.nodes.handle_moved": "Maniglia spostata.",
  "draw.nodes.bent": "Segmento piegato.",
  "draw.nodes.inserted.one": "{count} nodo aggiunto.",
  "draw.nodes.inserted.other": "{count} nodi aggiunti.",
  "draw.nodes.insert.none": "Aggiungere nodi chiede due nodi vicini scelti: il nodo nuovo va a metà del segmento fra loro.",
  "draw.nodes.deleted.one": "{count} nodo eliminato.",
  "draw.nodes.deleted.other": "{count} nodi eliminati.",
  "draw.nodes.deleted.all": "Senza nodi il tracciato non c’è più: eliminato.",
  "draw.nodes.made.corner.one": "{count} nodo a spigolo.",
  "draw.nodes.made.corner.other": "{count} nodi a spigolo.",
  "draw.nodes.made.smooth.one": "{count} nodo liscio.",
  "draw.nodes.made.smooth.other": "{count} nodi lisci.",
  "draw.nodes.made.symmetric.one": "{count} nodo simmetrico.",
  "draw.nodes.made.symmetric.other": "{count} nodi simmetrici.",
  "draw.nodes.kind.none": "Il tipo è dei nodi in mezzo al tracciato: i capi di un tracciato aperto non ne hanno.",
  "draw.nodes.lines.one": "{count} segmento ora è una linea.",
  "draw.nodes.lines.other": "{count} segmenti ora sono linee.",
  "draw.nodes.curves.one": "{count} segmento ora è una curva.",
  "draw.nodes.curves.other": "{count} segmenti ora sono curve.",
  "draw.nodes.links.none": "Cambiare i segmenti chiede due nodi vicini scelti.",
  "draw.nodes.broken.one": "Tracciato spezzato in {count} nodo.",
  "draw.nodes.broken.other": "Tracciato spezzato in {count} nodi.",
  "draw.nodes.break.none": "Spezzare chiede un nodo scelto in mezzo al tracciato, o su un tracciato chiuso.",
  "draw.nodes.joined": "Capi uniti: il tracciato ora è uno solo.",
  "draw.nodes.closed": "Capi uniti: il tracciato ora è chiuso.",
  "draw.nodes.join.none": "Unire chiede due capi scelti di tracciati aperti.",
  "draw.action.nodes_move": "Spostamento di nodi",
  "draw.action.handle": "Spostamento di una maniglia",
  "draw.action.bend": "Piegatura di un segmento",
  "draw.action.nodes_insert": "Aggiunta di nodi",
  "draw.action.nodes_delete": "Eliminazione di nodi",
  "draw.action.nodes_kind": "Tipo dei nodi",
  "draw.action.segments": "Tipo dei segmenti",
  "draw.action.nodes_break": "Tracciato spezzato",
  "draw.action.nodes_join": "Unione dei capi",
  "draw.keys.nodes.nudge": "Sposta i nodi scelti di 1, con Maiusc di 10, con Ctrl o ⌘ di un pixel",
  "draw.keys.nodes.nudge.grid": "Sposta i nodi scelti alla riga seguente della griglia, a cinque righe con Maiusc; liberi di un pixel con Ctrl o ⌘",
  "draw.keys.nodes.walk": "Il nodo dopo o prima",
  "draw.keys.nodes.ends": "Il primo o l’ultimo nodo",
  "draw.keys.nodes.all": "Sceglie tutti i nodi",
  "draw.keys.nodes.deselect": "Toglie la scelta dei nodi, poi quella dell’oggetto",
  "draw.keys.nodes.bar": "Va alla barra dei nodi",
  "draw.tool.bezier": "Bézier",
  "draw.tool.bezier.hint": "Disegna un tracciato nodo per nodo: un tocco mette uno spigolo, un trascinamento un nodo con le maniglie, e con Maiusc gli angoli vanno a passi di 15°. Tocca il primo nodo per chiudere il tracciato, l’ultimo o Invio per concluderlo; Canc toglie l’ultimo nodo.",
  "draw.bezier.node": "Nodo {index}, {kind}: x {x}, y {y}.",
  "draw.bezier.deleted": "Nodo {index} eliminato.",
  "draw.bezier.step.node": "Nodo {index}",
  "draw.bezier.step.handle": "Maniglia del nodo {index}",
  "draw.bezier.step.delete": "Eliminazione del nodo {index}",
  "draw.bezier.short": "Un tracciato vuole almeno due nodi in punti diversi: non c’è niente da scrivere.",
  "draw.bezier.cursor.close": "Primo nodo, Spazio chiude il tracciato",
  "draw.bezier.cursor.last": "Ultimo nodo, Spazio conclude il tracciato",
  "draw.added.path": "Tracciato aggiunto.",
  "draw.added.path.closed": "Tracciato chiuso aggiunto.",
  "draw.action.bezier": "Tracciato",
  "draw.keys.bezier.node": "Un nodo dove è il cursore: Spazio e di nuovo Spazio per uno spigolo, o in mezzo le frecce per tirarne le maniglie",
  "draw.keys.bezier.angle": "Tenuto, porta il nodo o la maniglia a passi di 15°",
  "draw.keys.bezier.finish": "Conclude il tracciato",
  "draw.keys.bezier.delete": "Elimina l’ultimo nodo",
  "draw.tool.lasso": "Lazo",
  "draw.tool.lasso.hint": "Disegna attorno agli oggetti da scegliere: si scelgono quelli che il lazo racchiude per intero. Con Maiusc li aggiungi alla selezione, con Alt li togli; un tocco sceglie l’oggetto sotto. Dalla tastiera, Spazio comincia il lazo dove è il cursore, le frecce lo tirano e Spazio lo chiude.",
  "draw.feature.selection": "Seleziona simili, isola i gruppi, blocca e nascondi",
  "draw.selection.menu": "Selezione avanzata",
  "draw.selection.empty": "Scegli prima degli oggetti.",
  "draw.select.all": "Seleziona tutto",
  "draw.select.invert": "Inverti la selezione",
  "draw.select.same_fill": "Stesso riempimento",
  "draw.select.same_stroke": "Stesso colore del contorno",
  "draw.select.same_width": "Stesso spessore del contorno",
  "draw.select.same_kind": "Stesso tipo di oggetto",
  "draw.select.same_tool": "Stesso strumento",
  "draw.select.same_layer": "Stesso livello",
  "draw.select.same.missing": "Gli oggetti scelti non hanno questa proprietà.",
  "draw.select.same_tool.none": "Vale per i tratti a mano libera: la stessa penna, o lo stesso evidenziatore, con la stessa punta.",
  "draw.lock": "Blocca",
  "draw.unlock": "Sblocca",
  "draw.hide": "Nascondi",
  "draw.show": "Mostra",
  "draw.unlock_all": "Sblocca tutto",
  "draw.show_all": "Mostra tutto",
  "draw.isolate": "Isola il gruppo",
  "draw.isolate.none": "Scegli un gruppo solo, o un collegamento, per isolarlo.",
  "draw.isolate.exit": "Esci dal gruppo",
  "draw.isolation": "Gruppo isolato",
  "draw.isolation.drawing": "Disegno",
  "draw.isolated": "Gruppo isolato: {name}. Si sceglie solo qui dentro; Esc esce.",
  "draw.isolation.left": "Fuori dal gruppo: si sceglie in tutto il disegno.",
  "draw.locked.one": "{count} oggetto bloccato: non si sceglie finché non lo sblocchi.",
  "draw.locked.other": "{count} oggetti bloccati: non si scelgono finché non li sblocchi.",
  "draw.hidden.one": "{count} oggetto nascosto: non si vede finché non lo mostri.",
  "draw.hidden.other": "{count} oggetti nascosti: non si vedono finché non li mostri.",
  "draw.unlocked.one": "{count} oggetto sbloccato.",
  "draw.unlocked.other": "{count} oggetti sbloccati.",
  "draw.unlocked.none": "Non c’è niente da sbloccare.",
  "draw.shown.one": "{count} oggetto di nuovo visibile.",
  "draw.shown.other": "{count} oggetti di nuovo visibili.",
  "draw.shown.none": "Non c’è niente di nascosto.",
  "draw.object.locked": "{name}: bloccato.",
  "draw.object.unlocked": "{name}: sbloccato.",
  "draw.object.hidden": "{name}: nascosto.",
  "draw.object.shown": "{name}: di nuovo visibile.",
  "draw.action.lock": "Blocco",
  "draw.action.unlock": "Sblocco",
  "draw.action.hide": "Oggetti nascosti",
  "draw.action.show": "Oggetti mostrati",
  "draw.keys.deep": "Tenuto col clic, sceglie l’oggetto dentro il gruppo",
  "draw.keys.isolate": "Isola il gruppo scelto",
  "draw.keys.isolate.exit": "Esce dal gruppo isolato, un gruppo alla volta",
  "draw.keys.lock": "Blocca la selezione; nell’albero blocca o sblocca la riga",
  "draw.keys.hide": "Nasconde la selezione; nell’albero nasconde o mostra la riga",
  "draw.keys.menu": "Apre il menu della selezione"
} as const;

/// Una chiave del catalogo del disegno.
export type DrawKey = keyof typeof IT;

/// L'inglese, completo per tipo come quello della shell.
const EN: Record<DrawKey, string> = {
  "draw.toolbar": "Drawing tools",
  "draw.surface": "Drawing sheet",
  "draw.tools": "Tool",
  "draw.colors": "Color",
  "draw.widths": "Width",
  "draw.edit": "Edit",
  "draw.view": "View",
  "draw.tool.select": "Select",
  "draw.tool.select.hint": "Tap an object to select it and drag it to move it; drag on empty space to select several with a box. Hold Shift to add or remove objects from the selection; arrow keys move by 1, with Shift by 10.",
  "draw.tool.pen": "Pen",
  "draw.tool.pen.hint": "Draw freehand; with a pen the width follows the pressure.",
  "draw.tool.highlighter": "Highlighter",
  "draw.tool.highlighter.hint": "Go over what you want to stand out: the mark is wide, of even width, and lets what it covers show through.",
  "draw.tool.eraser": "Eraser",
  "draw.tool.eraser.hint": "Removes the whole objects you cross.",
  "draw.tool.rect": "Rectangle",
  "draw.tool.rect.hint": "Drag to draw a rectangle; hold Shift for a square.",
  "draw.tool.ellipse": "Ellipse",
  "draw.tool.ellipse.hint": "Drag to draw an ellipse; hold Shift for a circle.",
  "draw.tool.line": "Line",
  "draw.tool.line.hint": "Drag to draw a line; hold Shift to snap the angle to 15° steps.",
  "draw.tool.arrow": "Arrow",
  "draw.tool.arrow.hint": "Drag to draw an arrow; hold Shift to snap the angle to 15° steps.",
  "draw.color.black": "Black",
  "draw.color.blue": "Blue",
  "draw.color.vermilion": "Vermilion",
  "draw.color.green": "Green",
  "draw.color.purple": "Purple",
  "draw.color.orange": "Orange",
  "draw.color.sky": "Sky blue",
  "draw.color.yellow": "Yellow",
  "draw.color.custom": "Custom {code}",
  "draw.color.custom.light": "Custom {code}, light: hard to read on white paper",
  "draw.color.more": "Other color…",
  "draw.color.dialog": "Custom color",
  "draw.color.code": "Color code",
  "draw.width.thin": "Thin",
  "draw.width.medium": "Medium",
  "draw.width.thick": "Thick",
  "draw.undo": "Undo",
  "draw.redo": "Redo",
  "draw.delete": "Delete selection",
  "draw.zoom_in": "Zoom in",
  "draw.zoom_out": "Zoom out",
  "draw.zoom_reset": "{zoom}: reset zoom to 100%",
  "draw.fit": "Show the whole drawing",
  "draw.title": "What did you draw?",
  "draw.title.placeholder": "For example: the home network",
  "draw.objects.one": "The drawing has {count} object.",
  "draw.objects.other": "The drawing has {count} objects.",
  "draw.selected.none": "Nothing selected.",
  "draw.selected.one": "{count} object selected.",
  "draw.selected.other": "{count} objects selected.",
  "draw.deleted.one": "{count} object deleted.",
  "draw.deleted.other": "{count} objects deleted.",
  "draw.erased.one": "{count} object erased.",
  "draw.erased.other": "{count} objects erased.",
  "draw.moved.one": "{count} object moved.",
  "draw.moved.other": "{count} objects moved.",
  "draw.added.stroke": "Stroke added.",
  "draw.added.highlight": "Highlight added.",
  "draw.added.rect": "Rectangle added.",
  "draw.added.ellipse": "Ellipse added.",
  "draw.added.line": "Line added.",
  "draw.added.arrow": "Arrow added.",
  "draw.announce.tool": "Tool: {tool}.",
  "draw.announce.color": "Color: {color}.",
  "draw.rejected": "Change not applied: {reason}.",
  "draw.reason.missing_target": "the object is gone",
  "draw.reason.missing_parent": "the layer is gone",
  "draw.reason.duplicate_id": "an identifier is already in use",
  "draw.reason.invalid": "the change is not valid",
  "draw.reason.locked": "the object is inside a locked layer or group",
  "draw.reason.foreign": "that part comes from another program and FubDraw leaves it as it is",
  "draw.reason.limit": "the drawing has reached its maximum size",
  "draw.reason.read_only": "the drawing is read-only",
  "draw.undone": "Undone: {action}.",
  "draw.redone": "Redone: {action}.",
  "draw.undo.failed": "Cannot undo “{action}”: the drawing has changed in the meantime.",
  "draw.redo.failed": "Cannot redo “{action}”: the drawing has changed in the meantime.",
  "draw.no_layer": "Every layer is locked or hidden: there is nowhere to draw.",
  "draw.ink_failed": "Could not save the stroke.",
  "draw.action.stroke": "Stroke",
  "draw.action.highlight": "Highlight",
  "draw.action.move": "Move",
  "draw.action.erase": "Erase",
  "draw.action.delete": "Delete",
  "draw.action.title": "Title",
  "draw.action.adopt": "Drawing made editable",
  "draw.adopted": "The drawing can now be edited.",
  "draw.kind.layer": "Layer",
  "draw.kind.group": "Group",
  "draw.kind.link": "Link",
  "draw.kind.stroke": "Stroke",
  "draw.kind.highlighter": "Highlight",
  "draw.kind.path": "Path",
  "draw.kind.circle": "Circle",
  "draw.kind.polyline": "Polyline",
  "draw.kind.polygon": "Polygon",
  "draw.kind.text": "Text",
  "draw.kind.image": "Image",
  "draw.describe.named": "{kind} “{name}”",
  "draw.describe.link": "{link} to “{note}”",
  "draw.describe.parts.one": "{count} object",
  "draw.describe.parts.other": "{count} objects",
  "draw.state.locked": "locked",
  "draw.state.hidden": "hidden",
  "draw.objects": "Objects",
  "draw.objects.empty": "The drawing is empty.",
  "draw.surface.hint": "Arrow keys move the cursor or the selection; Space presses and releases; Tab goes to the next object; Enter opens properties; ? lists the keys.",
  "draw.properties": "Properties",
  "draw.properties.selection": "Position and size",
  "draw.properties.document": "Drawing properties",
  "draw.properties.look": "Appearance",
  "draw.properties.text": "Text",
  "draw.properties.arrange": "Arrange",
  "draw.properties.transform": "Transform",
  "draw.properties.document_section": "Document",
  "draw.properties.align": "Align",
  "draw.properties.distribute": "Distribute",
  "draw.properties.apply": "Apply",
  "draw.properties.mixed": "Mixed",
  "draw.properties.none": "None",
  "draw.properties.fill": "Fill",
  "draw.properties.stroke": "Stroke",
  "draw.properties.ratio": "Keep proportions",
  "draw.properties.swatches": "{label}: swatches",
  "draw.properties.picker": "{label}: system picker",
  "draw.properties.problem.empty": "Type a value.",
  "draw.properties.problem.syntax": "Type a number or a calculation, like 120+15.",
  "draw.properties.problem.unit": "This field accepts these units: {units}.",
  "draw.properties.problem.relative": "The values differ, so a percentage has nothing to be part of: type a number.",
  "draw.properties.problem.finite": "The result isn’t a number: perhaps a division by zero.",
  "draw.properties.problem.paint": "Type a color: a code like #0072b2, a name like red, or “none”.",
  "draw.properties.problem.mixed": "The values differ: type the one to give them all.",
  "draw.properties.drawing": "The drawing",
  "draw.properties.rotation": "Rotation",
  "draw.properties.stroke_width": "Stroke width",
  "draw.properties.opacity": "Opacity",
  "draw.properties.dash": "Dashes",
  "draw.properties.cap": "Ends",
  "draw.properties.join": "Corners",
  "draw.properties.family": "Font",
  "draw.properties.family.default": "Default",
  "draw.properties.size": "Size",
  "draw.properties.anchor": "Alignment",
  "draw.properties.anchor.start": "Left",
  "draw.properties.anchor.middle": "Center",
  "draw.properties.anchor.end": "Right",
  "draw.properties.turn": "Clockwise rotation",
  "draw.properties.scale_x": "Horizontal scale",
  "draw.properties.scale_y": "Vertical scale",
  "draw.properties.skew_x": "Horizontal skew",
  "draw.properties.skew_y": "Vertical skew",
  "draw.properties.unit": "Units",
  "draw.properties.zero_scale": "A scale of zero percent would flatten the objects: type a value other than zero.",
  "draw.feature.properties": "Properties panel",
  "draw.bar.beside": "Toolbar beside the selection",
  "draw.bar.beside.on": "The selection toolbar sits beside the selection.",
  "draw.bar.beside.off": "The selection toolbar sits at the top of the sheet.",
  "draw.action.fill": "Fill",
  "draw.action.outline_color": "Stroke color",
  "draw.action.stroke_width": "Stroke width",
  "draw.action.opacity": "Opacity",
  "draw.action.font": "Font",
  "draw.action.font_size": "Text size",
  "draw.action.text_align": "Text alignment",
  "draw.action.page_size": "Page size",
  "draw.action.desc": "Description",
  "draw.keys.properties.panel": "Goes to the properties panel",
  "draw.keys.properties.step": "In a number field: up or down by 1, with Shift by 10",
  "draw.keys.properties.apply": "Applies the field’s value",
  "draw.keys.properties.text": "In the description: applies the text",
  "draw.keys.properties.revert": "Restores the field; again, goes back to the sheet",
  "draw.keys.attributes.focus": "Goes to the attributes, in the properties panel",
  "draw.field.width": "Width",
  "draw.field.height": "Height",
  "draw.field.title": "Title",
  "draw.field.desc": "Description",
  "draw.field.page_width": "Page width",
  "draw.field.page_height": "Page height",
  "draw.keys": "Drawing keys",
  "draw.keys.tools": "Tools",
  "draw.keys.cursor": "Drawing with the keyboard",
  "draw.keys.cursor.move": "Move the cursor: 10 px, 50 with Shift, 1 with Ctrl or ⌘",
  "draw.keys.cursor.press": "Press, then release",
  "draw.keys.cancel": "Cancel the gesture",
  "draw.keys.nudge": "Move the selection by 1, with Shift by 10",
  "draw.keys.resize": "Resize the selection by 1, with Shift by 10",
  "draw.keys.rotate": "Rotate the selection 15° counterclockwise or clockwise, with Shift 90°",
  "draw.keys.walk": "Next or previous object",
  "draw.keys.ends": "First or last object",
  "draw.keys.all": "Select all",
  "draw.keys.deselect": "Clear the selection",
  "draw.keys.actual": "Zoom to 100%",
  "draw.cursor.at": "x {x}, y {y}",
  "draw.cursor.down": "Pressed: arrows trace, Space releases, Esc cancels.",
  "draw.cursor.up": "Released.",
  "draw.resized": "Size: {width} × {height}.",
  "draw.walk": "{object}, {index} of {count}.",
  "draw.action.resize": "Resize",
  "draw.action.rotate": "Rotate",
  "draw.rotated.clockwise": "Rotated {angle} clockwise.",
  "draw.rotated.counter": "Rotated {angle} counterclockwise.",
  "draw.keys.paste": "Paste an image",
  "draw.action.image": "Image",
  "draw.added.image.one": "Image added.",
  "draw.added.image.other": "{count} images added.",
  "draw.image.heavy.one": "Image too large",
  "draw.image.heavy.other": "Images too large",
  "draw.image.large": "The image is {size}, and an image in a drawing can be at most {limit}. Reduce it? It will have fewer pixels, but the same size on the sheet.",
  "draw.image.shared": "The images are {size} in all, and images added together can be at most {limit}. Reduce them? They will have fewer pixels, but the same size on the sheet.",
  "draw.image.room": "The drawing has room for {limit} of images, and {size} are needed. Reduce? The images will have fewer pixels, but the same size on the sheet.",
  "draw.image.reduce": "Reduce",
  "draw.image.reducing": "Reducing the image…",
  "draw.image.unreadable": "This is not an image the drawing can read.",
  "draw.image.full": "The drawing is close to its {limit} limit: another image does not fit.",
  "draw.image.failed": "Could not reduce the image.",
  "draw.insert": "Insert",
  "draw.image.vault": "Image from the vault…",
  "draw.image.gone": "The chosen image does not open: it may no longer be in the vault.",
  "draw.arrange": "Arrange",
  "draw.duplicate": "Duplicate",
  "draw.group": "Group",
  "draw.ungroup": "Ungroup",
  "draw.order": "Order",
  "draw.order.front": "Bring to front",
  "draw.order.forward": "Bring forward",
  "draw.order.backward": "Send backward",
  "draw.order.back": "Send to back",
  "draw.align": "Align and distribute",
  "draw.align.left": "Align left",
  "draw.align.center": "Align center",
  "draw.align.right": "Align right",
  "draw.align.top": "Align top",
  "draw.align.middle": "Align middle",
  "draw.align.bottom": "Align bottom",
  "draw.align.to_page": "{action}, relative to the page",
  "draw.distribute.x": "Distribute horizontally",
  "draw.distribute.y": "Distribute vertically",
  "draw.distribute.few": "Needs at least three objects.",
  "draw.action.duplicate": "Duplicate",
  "draw.action.order": "Reorder",
  "draw.action.group": "Group",
  "draw.action.ungroup": "Ungroup",
  "draw.action.align": "Align",
  "draw.action.distribute": "Distribute",
  "draw.duplicated.one": "{count} object duplicated.",
  "draw.duplicated.other": "{count} objects duplicated.",
  "draw.duplicate.foreign": "Not duplicated: an object has parts from another program that FubDraw cannot copy.",
  "draw.ordered.front": "Brought to front.",
  "draw.ordered.forward": "Brought forward.",
  "draw.ordered.backward": "Sent backward.",
  "draw.ordered.back": "Sent to back.",
  "draw.grouped": "Grouped {count} objects.",
  "draw.group.few": "A group needs at least two objects.",
  "draw.ungrouped.one": "{count} group ungrouped.",
  "draw.ungrouped.other": "{count} groups ungrouped.",
  "draw.ungroup.none": "None of the selected objects is a group.",
  "draw.ungroup.foreign": "Not ungrouped: the group has parts from another program that would not follow its position or style.",
  "draw.aligned.one": "{count} object aligned.",
  "draw.aligned.other": "{count} objects aligned.",
  "draw.distributed": "{count} objects distributed.",
  "draw.unchanged": "Already like that: nothing to change.",
  "draw.keys.arrange": "Go to the selection bar",
  "draw.surface.hint.arrange": "Arrow keys move the cursor or the selection; Space presses and releases; Tab goes to the next object; Enter opens properties; with a selection, Alt+F10 goes to the commands that arrange it; ? lists the keys.",
  "draw.layers": "Layers",
  "draw.layers.current": "Layers: drawing in “{name}”",
  "draw.layers.none": "Layers: the drawing has none",
  "draw.layers.none.short": "No layers",
  "draw.layer.default": "Layer {n}",
  "draw.layer.unnamed": "Unnamed layer",
  "draw.layer.new": "New layer",
  "draw.layer.rename": "Rename “{name}”…",
  "draw.layer.hide": "Hide “{name}”",
  "draw.layer.show": "Show “{name}”",
  "draw.layer.lock": "Lock “{name}”",
  "draw.layer.unlock": "Unlock “{name}”",
  "draw.layer.up": "Move “{name}” up",
  "draw.layer.down": "Move “{name}” down",
  "draw.layer.delete": "Delete “{name}”",
  "draw.layer.delete.last": "It is the only layer.",
  "draw.layer.delete.locked": "It is locked: unlock it to delete it.",
  "draw.layer.rename.dialog": "Rename layer",
  "draw.layer.name": "Layer name",
  "draw.layer.chosen": "Drawing in “{name}”.",
  "draw.layer.locked_here": "“{name}” is locked: unlock it, or choose another layer, to draw.",
  "draw.layer.hidden_here": "“{name}” is hidden: show it, or choose another layer, to draw.",
  "draw.layer.flat": "“{name}” has a transform that flattens it: you cannot draw in it.",
  "draw.layer.added": "Layer “{name}” created: drawing there.",
  "draw.layer.renamed": "The layer is now called “{name}”.",
  "draw.layer.hidden": "“{name}” hidden.",
  "draw.layer.shown": "“{name}” visible again.",
  "draw.layer.locked": "“{name}” locked.",
  "draw.layer.unlocked": "“{name}” unlocked.",
  "draw.layer.moved_up": "“{name}” is now above “{other}”.",
  "draw.layer.moved_down": "“{name}” is now below “{other}”.",
  "draw.layer.deleted": "“{name}” deleted.",
  "draw.layer.deleted.one": "“{name}” deleted, with {count} object.",
  "draw.layer.deleted.other": "“{name}” deleted, with {count} objects.",
  "draw.action.layer_add": "New layer",
  "draw.action.layer_rename": "Layer name",
  "draw.action.layer_hide": "Hide layer",
  "draw.action.layer_show": "Show layer",
  "draw.action.layer_lock": "Lock layer",
  "draw.action.layer_unlock": "Unlock layer",
  "draw.action.layer_order": "Layer order",
  "draw.action.layer_delete": "Delete layer",
  "draw.action.into_layer": "Move to layer",
  "draw.into_layer": "Move to layer",
  "draw.into_layer.here": "The selected objects are already here.",
  "draw.moved_to_layer.one": "{count} object moved to “{name}”.",
  "draw.moved_to_layer.other": "{count} objects moved to “{name}”.",
  "draw.state.current": "current",
  "draw.page_grid": "Page and grid",
  "draw.grid.show": "Show grid",
  "draw.grid.snap": "Snap to grid",
  "draw.grid.snap.free": "Hold {key} while dragging to place freely.",
  "draw.grid.step": "Spacing {step}",
  "draw.grid.shown": "Grid shown.",
  "draw.grid.hidden": "Grid hidden.",
  "draw.grid.snap.on": "Snap to grid on.",
  "draw.grid.snap.off": "Snap to grid off.",
  "draw.grid.stepped": "Grid spacing: {step}.",
  "draw.guides.hint": "Aligns to the edges and centers of other objects and of the page. Hold {key} while dragging to place freely.",
  "draw.guides.on": "Smart guides on.",
  "draw.guides.off": "Smart guides off.",
  "draw.guides.snapped": "Snapped: {parts}.",
  "draw.guides.object": "{source} in line with {edge} of {name}",
  "draw.guides.object.same": "{source} in line with that of {name}",
  "draw.guides.page": "{source} in line with {edge} of the page",
  "draw.guides.page.same": "{source} in line with that of the page",
  "draw.guides.node": "{source} in line with a node",
  "draw.guides.spaced.x": "evenly spaced horizontally, {gap}",
  "draw.guides.spaced.y": "evenly spaced vertically, {gap}",
  "draw.guides.edge.left": "the left edge",
  "draw.guides.edge.center_x": "the horizontal center",
  "draw.guides.edge.right": "the right edge",
  "draw.guides.edge.top": "the top edge",
  "draw.guides.edge.center_y": "the vertical center",
  "draw.guides.edge.bottom": "the bottom edge",
  "draw.guides.edge.point": "the point",
  "draw.page.fit": "Fit page to drawing",
  "draw.page.fit.empty": "The drawing is empty.",
  "draw.page.fit.already": "The page already fits the drawing.",
  "draw.page.fitted": "Page fitted: {width} × {height}.",
  "draw.action.fit_page": "Fit page to drawing",
  "draw.keys.grid": "Grid",
  "draw.keys.grid.show": "Show or hide the grid",
  "draw.keys.grid.snap": "Turn snap to grid on or off",
  "draw.keys.grid.free": "Held while dragging: place freely, off the grid",
  "draw.keys.guides": "Smart guides",
  "draw.keys.guides.free": "Held while dragging: place freely, without snapping to other objects",
  "draw.keys.guides.measure": "Held with a selection: the distances to the object under the pointer, or to the page",
  "draw.keys.cursor.move.grid": "Move the cursor to the next grid line, five lines with Shift; freely by 1 px with Ctrl or ⌘",
  "draw.keys.nudge.grid": "Move the selection to the next grid line, five lines with Shift",
  "draw.keys.resize.grid": "Resize the selection to the next grid line, five lines with Shift",
  "draw.rulers.show": "Show rulers",
  "draw.rulers.hide": "Hide rulers",
  "draw.rulers.shown": "Rulers shown.",
  "draw.rulers.hidden": "Rulers hidden.",
  "draw.rulers.guides.show": "Show guides",
  "draw.rulers.guides.hint": "The guides dragged from the rulers: whatever moves snaps to them while they are shown.",
  "draw.rulers.guides.shown": "Guides shown.",
  "draw.rulers.guides.hidden": "Guides hidden.",
  "draw.units.item": "Units: {unit}…",
  "draw.unit.px": "Pixels",
  "draw.unit.mm": "Millimeters",
  "draw.unit.cm": "Centimeters",
  "draw.unit.in": "Inches",
  "draw.unit.pt": "Points",
  "draw.unit.pt.one": "{value} point",
  "draw.unit.pt.other": "{value} points",
  "draw.units.now.px": "The document now measures in pixels.",
  "draw.units.now.mm": "The document now measures in millimeters.",
  "draw.units.now.cm": "The document now measures in centimeters.",
  "draw.units.now.in": "The document now measures in inches.",
  "draw.units.now.pt": "The document now measures in points.",
  "draw.units.hint": "Rulers, fields and measurements. The drawing does not change.",
  "draw.action.units": "Document units",
  "draw.action.guide_add": "New guide",
  "draw.action.guide_move": "Guide move",
  "draw.action.guide_delete": "Guide deletion",
  "draw.action.guide_lock": "Guide locked",
  "draw.action.guide_unlock": "Guide unlocked",
  "draw.action.guides": "Guides",
  "draw.guide.added.x": "Vertical guide added at {at}.",
  "draw.guide.added.y": "Horizontal guide added at {at}.",
  "draw.guide.moved.x": "Vertical guide moved to {at}.",
  "draw.guide.moved.y": "Horizontal guide moved to {at}.",
  "draw.guide.deleted.x": "Vertical guide deleted.",
  "draw.guide.deleted.y": "Horizontal guide deleted.",
  "draw.guide.locked": "Guide locked.",
  "draw.guide.unlocked": "Guide unlocked.",
  "draw.guide.drop": "Release to delete",
  "draw.guide.lock": "Lock guide",
  "draw.guide.unlock": "Unlock guide",
  "draw.guide.delete": "Delete guide",
  "draw.guides.line": "{source} in line with a guide",
  "draw.guides.lock_all": "Lock all guides",
  "draw.guides.unlock_all": "Unlock all guides",
  "draw.guides.delete_all": "Delete all guides",
  "draw.guides.all_locked": "Guides locked.",
  "draw.guides.all_unlocked": "Guides unlocked.",
  "draw.guides.deleted.one": "{count} guide deleted.",
  "draw.guides.deleted.other": "{count} guides deleted.",
  "draw.guides.changed": "Guides updated.",
  "draw.guides.full": "The document already has {count} guides, as many as it can hold.",
  "draw.guides.unreadable": "The guides written in the file can’t be read: they stay as they are until you rewrite them here.",
  "draw.guides.dialog": "Guides…",
  "draw.guides.dialog.title": "Guides",
  "draw.guides.dialog.empty": "The document has no guides. Add one here, or drag one from a ruler.",
  "draw.guides.dialog.hint": "Positions start from the rulers’ zero: vertical guides to the right, horizontal ones downward.",
  "draw.guides.column.axis": "Direction",
  "draw.guides.column.position": "Position",
  "draw.guides.axis_label": "Direction of guide {index}",
  "draw.guides.vertical": "Vertical",
  "draw.guides.horizontal": "Horizontal",
  "draw.guides.position": "Position of guide {index}, {axis}",
  "draw.guides.locked_field": "Locked",
  "draw.guides.locked_label": "Guide {index}, {axis}: locked",
  "draw.guides.delete_label": "Delete guide {index}, {axis}",
  "draw.guides.add_x": "Add a vertical one",
  "draw.guides.add_y": "Add a horizontal one",
  "draw.guides.invalid": "Write the position of guide {index} as a number.",
  "draw.keys.rulers": "Rulers and guides",
  "draw.keys.rulers.show": "Shows or hides the rulers",
  "draw.keys.rulers.guides": "Shows or hides the guides",
  "draw.keys.rulers.free": "Held while dragging a guide: place freely, without snapping",
  "draw.tool.text": "Text",
  "draw.tool.text.hint": "Tap the sheet to write a text, or a text to change it. Enter starts a new line; Escape finishes.",
  "draw.sizes": "Size",
  "draw.size.small": "Small",
  "draw.size.medium": "Medium",
  "draw.size.large": "Large",
  "draw.text.new": "New text",
  "draw.text.change": "Text",
  "draw.text.hint": "Enter starts a new line; Escape, Tab or {key}+Enter finish.",
  "draw.text.edit": "Edit text",
  "draw.action.text": "Text",
  "draw.action.text_edit": "Text edit",
  "draw.added.text": "Text added.",
  "draw.text.edited": "Text changed.",
  "draw.text.none": "Select a text to edit.",
  "draw.keys.text": "Text",
  "draw.keys.text.write": "With the Text tool: write where the cursor is, or change the text there",
  "draw.keys.text.edit": "Edit the selected text",
  "draw.keys.text.newline": "Start a new line, while writing",
  "draw.keys.text.finish": "Finish the text, while writing",
  "draw.link": "Link to a note…",
  "draw.link.change": "Change link…",
  "draw.link.open": "Open “{note}”",
  "draw.unlink": "Remove link",
  "draw.action.link": "Link",
  "draw.action.relink": "Link change",
  "draw.action.unlink": "Link removal",
  "draw.linked": "Linked to “{note}”.",
  "draw.relinked": "The link now goes to “{note}”.",
  "draw.unlinked.one": "{count} link removed.",
  "draw.unlinked.other": "{count} links removed.",
  "draw.unlink.none": "None of the selected objects is a link.",
  "draw.unlink.foreign": "Not removed: the link has parts from another program that would not follow its position or style.",
  "draw.link.nested": "Not linked: a selected object already is a link, and a link cannot hold another. Remove it first, or select it alone to change it.",
  "draw.link.open.none": "Select a link to open its note.",
  "draw.keys.link": "Link to a note, or change the selected link",
  "draw.keys.link.open": "Open the note of the selected link",
  "draw.level.essential": "Essential",
  "draw.level.standard": "Standard",
  "draw.level.expert": "Expert",
  "draw.level.custom": "Custom",
  "draw.keys.from_level": "{group} · from the {level} level",
  "draw.keys.more": "The current level is “{level}”. The keys below work from a higher level, chosen in Settings, in the “Drawings” group.",
  "draw.keys.more.custom": "The current level is “Custom”. The keys below belong to parts it does not have: add them in Settings, in the “Drawings” group.",
  "draw.feature.colors": "Custom colors",
  "draw.feature.arrange": "Duplicate, group, order, align and distribute",
  "draw.feature.layers": "Layers",
  "draw.feature.grid": "Page and grid",
  "draw.feature.guides": "Smart guides",
  "draw.feature.rulers": "Rulers and guides",
  "draw.feature.links": "Links to notes",
  "draw.feature.images": "Images from the vault",
  "draw.feature.attributes": "Attributes",
  "draw.feature.outline": "Outline: dashes, ends and corners",
  "draw.feature.transform": "Transform: rotation, scale and skew",
  "draw.feature.apply": "Apply transform",
  "draw.feature.path": "Object to path",
  "draw.feature.boolean": "Boolean operations",
  "draw.attributes": "Attributes",
  "draw.attributes.subject": "{object}, {tag} element",
  "draw.attributes.none": "Select an object to see its attributes.",
  "draw.attributes.many": "{count} objects are selected: select one to see its attributes.",
  "draw.attributes.name": "Attribute",
  "draw.attributes.value": "Value",
  "draw.attributes.actions": "Remove",
  "draw.attributes.id.none": "no id",
  "draw.attributes.remove": "Remove {key}",
  "draw.attributes.add.title": "Add an attribute",
  "draw.attributes.add.key": "Attribute name",
  "draw.attributes.add.value": "Value of {key}",
  "draw.attributes.add": "Add",
  "draw.attributes.added": "{key} added.",
  "draw.attributes.changed": "{key} changed.",
  "draw.attributes.removed": "{key} removed.",
  "draw.attributes.renamed": "The id is now “{id}”.",
  "draw.attributes.size": "The value is {size} characters long: the first {shown} are shown here.",
  "draw.attributes.note.ink": "It comes from the stroke’s ink: redraw the stroke to change it.",
  "draw.attributes.note.arrow": "It comes from the arrow’s geometry: move its ends to change it.",
  "draw.attributes.note.fubdraw": "FubDraw writes it.",
  "draw.attributes.note.link": "Change it with “Change link…”.",
  "draw.attributes.note.image": "It says where the image comes from, and is read-only here.",
  "draw.attributes.note.namespace": "It belongs to another program: FubDraw keeps it as it is.",
  "draw.attributes.note.long": "It is too long to change here.",
  "draw.attributes.problem.empty": "Enter a value, or remove the attribute.",
  "draw.attributes.problem.paint": "Enter a color such as #0072b2, or none.",
  "draw.attributes.problem.length": "Enter a number, such as 12 or -4.5.",
  "draw.attributes.problem.size": "Enter a non-negative number, such as 12 or 0.5.",
  "draw.attributes.problem.opacity": "Enter a number from 0 to 1, such as 0.5.",
  "draw.attributes.problem.dashes": "Enter none, or lengths separated by spaces, such as 4 2.",
  "draw.attributes.problem.keyword": "Choose one of the listed values.",
  "draw.attributes.problem.family": "Choose one of the listed fonts.",
  "draw.attributes.problem.transform": "Enter an SVG transform, such as translate(10 20) or rotate(45).",
  "draw.attributes.problem.points": "Enter pairs of numbers, such as 0,0 10,0 10,10.",
  "draw.attributes.problem.path": "Enter an SVG path, such as M0 0 L10 10.",
  "draw.attributes.problem.aspect": "Enter an alignment such as xMidYMid, followed if needed by meet or slice.",
  "draw.attributes.problem.identity": "That transform changes nothing: there is nothing to add.",
  "draw.attributes.id.empty": "An id cannot be empty.",
  "draw.attributes.id.long": "An id has at most {max} characters.",
  "draw.attributes.id.form": "An id starts with a letter or _, followed by letters, digits, _, . and -.",
  "draw.attributes.id.reserved": "Ids starting with fub- belong to FubDraw.",
  "draw.attributes.id.taken": "“{id}” is already the id of another element.",
  "draw.attributes.id.cited": "A part from another program refers to “{id}”: changing it would break the reference.",
  "draw.action.attribute": "Attribute change",
  "draw.action.rename": "Id change",
  "draw.keys.attributes.toggle": "Show or hide the attributes of the selected object",
  "draw.keys.attributes.apply": "Apply the value",
  "draw.keys.attributes.newline": "New line, in points and paths",
  "draw.keys.attributes.revert": "Restore the value; again, back to the drawing sheet",
  "draw.outline": "Outline",
  "draw.outline.solid": "Solid",
  "draw.outline.dashed": "Dashed",
  "draw.outline.dotted": "Dotted",
  "draw.outline.dashdot": "Dash-dot",
  "draw.outline.custom": "Custom: {value}",
  "draw.outline.butt": "Flat ends",
  "draw.outline.round_cap": "Round ends",
  "draw.outline.square": "Square ends",
  "draw.outline.miter": "Sharp corners",
  "draw.outline.round_join": "Round corners",
  "draw.outline.bevel": "Beveled corners",
  "draw.outline.none": "None of the selected objects has an outline.",
  "draw.outlined.one": "{style}: one outline.",
  "draw.outlined.other": "{style}: {count} outlines.",
  "draw.action.dash": "Dash pattern",
  "draw.action.cap": "Outline ends",
  "draw.action.join": "Outline corners",
  "draw.transform": "Transform…",
  "draw.transform.title": "Transform",
  "draw.transform.message": "Around the center of the selected objects: first the scale, then the skew, then the rotation. A negative scale mirrors.",
  "draw.transform.rotate": "Clockwise rotation (°)",
  "draw.transform.scale_x": "Horizontal scale (%)",
  "draw.transform.scale_y": "Vertical scale (%)",
  "draw.transform.skew_x": "Horizontal skew (°)",
  "draw.transform.skew_y": "Vertical skew (°)",
  "draw.transform.unwritable": "An object would become too small to write its transform: nothing changed.",
  "draw.transformed.one": "{count} object transformed.",
  "draw.transformed.other": "{count} objects transformed.",
  "draw.action.transform": "Transform",
  "draw.apply_transform": "Apply transform",
  "draw.applied.one": "Transform applied to {count} object.",
  "draw.applied.other": "Transform applied to {count} objects.",
  "draw.applied.kept.one": "{count} object keeps a transform its shape cannot express.",
  "draw.applied.kept.other": "{count} objects keep a transform their shape cannot express.",
  "draw.action.apply_transform": "Apply transform",
  "draw.to_path": "Object to path",
  "draw.traced.one": "{count} object became a path.",
  "draw.traced.other": "{count} objects became paths.",
  "draw.traced.refused.one": "{count} object stays as it is: text, images and empty shapes don’t become paths.",
  "draw.traced.refused.other": "{count} objects stay as they are: text, images and empty shapes don’t become paths.",
  "draw.action.to_path": "Object to path",
  "draw.boolean": "Boolean operations",
  "draw.boolean.union": "Union",
  "draw.boolean.difference": "Difference",
  "draw.boolean.intersection": "Intersection",
  "draw.boolean.exclusion": "Exclusion",
  "draw.boolean.division": "Division",
  "draw.boolean.few": "Needs at least two shapes.",
  "draw.boolean.not_shapes.one": "Boolean operations work on shapes: {count} selected object isn’t one.",
  "draw.boolean.not_shapes.other": "Boolean operations work on shapes: {count} selected objects aren’t.",
  "draw.boolean.empty": "The result would be empty: nothing changed.",
  "draw.boolean.whole": "The other shapes don’t divide the bottom one: nothing changed.",
  "draw.boolean.foreign": "The bottom shape has attributes from another program that FubDraw cannot rewrite: nothing changed.",
  "draw.boolean.failed": "The computation fails on these shapes: nothing changed.",
  "draw.combined.one": "{action}: {count} shape becomes one path.",
  "draw.combined.other": "{action}: {count} shapes become one path.",
  "draw.divided": "Division: the shape becomes {count} paths.",
  "draw.action.union": "Union",
  "draw.action.difference": "Difference",
  "draw.action.intersection": "Intersection",
  "draw.action.exclusion": "Exclusion",
  "draw.action.division": "Division",
  "draw.tool.nodes": "Nodes",
  "draw.tool.nodes.hint": "Edit the nodes of the selected path: drag a node, a handle or a segment, or drag on empty space to select several nodes with a box. Hold Shift to add or remove nodes; double-tap a segment to add a node; arrow keys move the selected nodes.",
  "draw.nodes.bar": "Node commands",
  "draw.nodes.insert": "Add nodes",
  "draw.nodes.delete": "Delete nodes",
  "draw.nodes.corner": "Corner nodes",
  "draw.nodes.smooth": "Smooth nodes",
  "draw.nodes.symmetric": "Symmetric nodes",
  "draw.nodes.line": "Segments to lines",
  "draw.nodes.curve": "Segments to curves",
  "draw.nodes.break": "Break at nodes",
  "draw.nodes.join": "Join ends",
  "draw.nodes.place": "Node position",
  "draw.nodes.walk": "Node {index} of {count}, {kind}: x {x}, y {y}.",
  "draw.nodes.kind.corner": "corner",
  "draw.nodes.kind.smooth": "smooth",
  "draw.nodes.kind.symmetric": "symmetric",
  "draw.nodes.kind.end": "end",
  "draw.nodes.shown.one": "{object}: {count} node to edit.",
  "draw.nodes.shown.other": "{object}: {count} nodes to edit.",
  "draw.nodes.selected.none": "No nodes selected.",
  "draw.nodes.selected.one": "{count} node selected.",
  "draw.nodes.selected.other": "{count} nodes selected.",
  "draw.nodes.no_path": "The selected object is not a path: “Object to path” makes its nodes editable.",
  "draw.nodes.many": "Select a single object to edit its nodes.",
  "draw.nodes.unreadable": "This path’s data cannot be read: its nodes cannot be edited.",
  "draw.nodes.flat": "This path is squashed onto a line: its nodes cannot be edited.",
  "draw.nodes.empty": "This path has no nodes.",
  "draw.nodes.moved.at": "Node moved: x {x}, y {y}.",
  "draw.nodes.moved.one": "{count} node moved.",
  "draw.nodes.moved.other": "{count} nodes moved.",
  "draw.nodes.handle_moved": "Handle moved.",
  "draw.nodes.bent": "Segment bent.",
  "draw.nodes.inserted.one": "{count} node added.",
  "draw.nodes.inserted.other": "{count} nodes added.",
  "draw.nodes.insert.none": "Adding nodes needs two neighbouring nodes selected: the new node goes halfway along the segment between them.",
  "draw.nodes.deleted.one": "{count} node deleted.",
  "draw.nodes.deleted.other": "{count} nodes deleted.",
  "draw.nodes.deleted.all": "With no nodes left the path is gone: deleted.",
  "draw.nodes.made.corner.one": "{count} corner node.",
  "draw.nodes.made.corner.other": "{count} corner nodes.",
  "draw.nodes.made.smooth.one": "{count} smooth node.",
  "draw.nodes.made.smooth.other": "{count} smooth nodes.",
  "draw.nodes.made.symmetric.one": "{count} symmetric node.",
  "draw.nodes.made.symmetric.other": "{count} symmetric nodes.",
  "draw.nodes.kind.none": "Only nodes inside a path have a type: the ends of an open path have none.",
  "draw.nodes.lines.one": "{count} segment is now a line.",
  "draw.nodes.lines.other": "{count} segments are now lines.",
  "draw.nodes.curves.one": "{count} segment is now a curve.",
  "draw.nodes.curves.other": "{count} segments are now curves.",
  "draw.nodes.links.none": "Changing segments needs two neighbouring nodes selected.",
  "draw.nodes.broken.one": "Path broken at {count} node.",
  "draw.nodes.broken.other": "Path broken at {count} nodes.",
  "draw.nodes.break.none": "Breaking needs a selected node inside the path, or on a closed path.",
  "draw.nodes.joined": "Ends joined: the path is now one.",
  "draw.nodes.closed": "Ends joined: the path is now closed.",
  "draw.nodes.join.none": "Joining needs two selected ends of open paths.",
  "draw.action.nodes_move": "Move nodes",
  "draw.action.handle": "Move handle",
  "draw.action.bend": "Bend segment",
  "draw.action.nodes_insert": "Add nodes",
  "draw.action.nodes_delete": "Delete nodes",
  "draw.action.nodes_kind": "Node type",
  "draw.action.segments": "Segment type",
  "draw.action.nodes_break": "Break path",
  "draw.action.nodes_join": "Join ends",
  "draw.keys.nodes.nudge": "Move the selected nodes by 1, with Shift by 10, with Ctrl or ⌘ by one pixel",
  "draw.keys.nodes.nudge.grid": "Move the selected nodes to the next grid line, five lines with Shift; freely by one pixel with Ctrl or ⌘",
  "draw.keys.nodes.walk": "Next or previous node",
  "draw.keys.nodes.ends": "First or last node",
  "draw.keys.nodes.all": "Select all nodes",
  "draw.keys.nodes.deselect": "Clear the node selection, then the object selection",
  "draw.keys.nodes.bar": "Go to the node bar",
  "draw.tool.bezier": "Bézier",
  "draw.tool.bezier.hint": "Draw a path node by node: a tap places a corner, a drag a node with handles, and with Shift the angles go in 15° steps. Tap the first node to close the path, the last one or press Enter to finish it; Delete removes the last node.",
  "draw.bezier.node": "Node {index}, {kind}: x {x}, y {y}.",
  "draw.bezier.deleted": "Node {index} deleted.",
  "draw.bezier.step.node": "Node {index}",
  "draw.bezier.step.handle": "Handle of node {index}",
  "draw.bezier.step.delete": "Delete node {index}",
  "draw.bezier.short": "A path needs at least two nodes in different places: there is nothing to write.",
  "draw.bezier.cursor.close": "First node, Space closes the path",
  "draw.bezier.cursor.last": "Last node, Space finishes the path",
  "draw.added.path": "Path added.",
  "draw.added.path.closed": "Closed path added.",
  "draw.action.bezier": "Path",
  "draw.keys.bezier.node": "A node at the cursor: Space and Space again for a corner, or the arrow keys in between to pull its handles",
  "draw.keys.bezier.angle": "Held, moves the node or the handle in 15° steps",
  "draw.keys.bezier.finish": "Finish the path",
  "draw.keys.bezier.delete": "Delete the last node",
  "draw.tool.lasso": "Lasso",
  "draw.tool.lasso.hint": "Draw around the objects to select: you select the ones the lasso fully encloses. With Shift you add them to the selection, with Alt you remove them; a tap selects the object underneath. From the keyboard, Space starts the lasso at the cursor, the arrow keys pull it and Space closes it.",
  "draw.feature.selection": "Select similar, isolate groups, lock and hide",
  "draw.selection.menu": "Advanced selection",
  "draw.selection.empty": "Select some objects first.",
  "draw.select.all": "Select all",
  "draw.select.invert": "Invert selection",
  "draw.select.same_fill": "Same fill",
  "draw.select.same_stroke": "Same stroke color",
  "draw.select.same_width": "Same stroke width",
  "draw.select.same_kind": "Same kind of object",
  "draw.select.same_tool": "Same tool",
  "draw.select.same_layer": "Same layer",
  "draw.select.same.missing": "The selected objects don’t have this property.",
  "draw.select.same_tool.none": "For freehand strokes: the same pen, or the same highlighter, with the same tip.",
  "draw.lock": "Lock",
  "draw.unlock": "Unlock",
  "draw.hide": "Hide",
  "draw.show": "Show",
  "draw.unlock_all": "Unlock all",
  "draw.show_all": "Show all",
  "draw.isolate": "Isolate group",
  "draw.isolate.none": "Select a single group, or a link, to isolate it.",
  "draw.isolate.exit": "Exit group",
  "draw.isolation": "Isolated group",
  "draw.isolation.drawing": "Drawing",
  "draw.isolated": "Isolated group: {name}. You select only inside it; Esc exits.",
  "draw.isolation.left": "Out of the group: you select across the whole drawing.",
  "draw.locked.one": "{count} object locked: it can’t be selected until you unlock it.",
  "draw.locked.other": "{count} objects locked: they can’t be selected until you unlock them.",
  "draw.hidden.one": "{count} object hidden: it stays out of sight until you show it.",
  "draw.hidden.other": "{count} objects hidden: they stay out of sight until you show them.",
  "draw.unlocked.one": "{count} object unlocked.",
  "draw.unlocked.other": "{count} objects unlocked.",
  "draw.unlocked.none": "There is nothing to unlock.",
  "draw.shown.one": "{count} object visible again.",
  "draw.shown.other": "{count} objects visible again.",
  "draw.shown.none": "There is nothing hidden.",
  "draw.object.locked": "{name}: locked.",
  "draw.object.unlocked": "{name}: unlocked.",
  "draw.object.hidden": "{name}: hidden.",
  "draw.object.shown": "{name}: visible again.",
  "draw.action.lock": "Lock",
  "draw.action.unlock": "Unlock",
  "draw.action.hide": "Hide objects",
  "draw.action.show": "Show objects",
  "draw.keys.deep": "Held while clicking, selects the object inside the group",
  "draw.keys.isolate": "Isolate the selected group",
  "draw.keys.isolate.exit": "Leave the isolated group, one group at a time",
  "draw.keys.lock": "Lock the selection; in the tree, lock or unlock the row",
  "draw.keys.hide": "Hide the selection; in the tree, hide or show the row",
  "draw.keys.menu": "Open the selection menu"
};

/// Il catalogo del disegno: `t` e `plural` come quelli della shell, sulle
/// chiavi del disegno.
export const drawStrings = catalog(IT, { en: EN });
export const { t, plural } = drawStrings;
