package esempio:view@0.1.0;

world view {
    import fub:abi/host-env@0.2.0;
    import fub:abi/host-vault-read@0.2.0;

    export fub:abi/plugin@0.2.0;
    export fub:abi/view@0.2.0;
    export fub:abi/format@0.2.0;
}
