// Le stringhe di «Importa disegno».
//
// Arrivano con la finestra dell'importazione (`dialog.ts`), che la shell
// carica con un `import()` quando qualcuno importa: chi non importa non le
// scarica. La lingua, la scala di ripiego, i nomi fra graffe sono quelli
// della shell (`catalog` in `i18n/strings.ts`). Ogni genere di nota del
// lettore (`NoteKind`) ha la sua frase, al singolare e al plurale: il
// rapporto dice che cosa c'era e che cosa diventa.

import { catalog } from "../../../i18n/strings";

/// Il catalogo italiano, che è anche la forma dell'inglese.
const IT = {
  "draw.import.title": "Importa disegno",
  "draw.import.from": "Da «{file}», un disegno di {program}.",
  "draw.import.reading": "Leggo il file…",
  "draw.import.preparing": "Preparo il disegno…",
  "draw.import.preview": "Anteprima del disegno importato",
  "draw.import.name": "Nome",
  "draw.import.folder": "Cartella",
  "draw.import.folder.placeholder": "Radice del vault",
  "draw.import.create": "Importa",
  "draw.import.count.shapes.one": "1 forma",
  "draw.import.count.shapes.other": "{count} forme",
  "draw.import.count.texts.one": "1 testo",
  "draw.import.count.texts.other": "{count} testi",
  "draw.import.count.lines.one": "1 linea",
  "draw.import.count.lines.other": "{count} linee",
  "draw.import.count.ink.one": "1 tratto a mano libera",
  "draw.import.count.ink.other": "{count} tratti a mano libera",
  "draw.import.count.images.one": "1 immagine",
  "draw.import.count.images.other": "{count} immagini",
  "draw.import.count.boards.one": "1 tavola",
  "draw.import.count.boards.other": "{count} tavole",
  "draw.import.count.layers.one": "1 livello",
  "draw.import.count.layers.other": "{count} livelli",
  "draw.import.report": "Che cosa cambia",
  "draw.import.report.none": "Entra tutto com’è.",
  "draw.import.note.sample": "Per esempio: «{sample}».",
  "draw.import.note.hand-font.one": "Un testo scritto con un carattere a mano passa a Inter.",
  "draw.import.note.hand-font.other": "{count} testi scritti con un carattere a mano passano a Inter.",
  "draw.import.note.rough.one": "Un oggetto dal tratto a schizzo si disegna con un tratto pulito.",
  "draw.import.note.rough.other": "{count} oggetti dal tratto a schizzo si disegnano con un tratto pulito.",
  "draw.import.note.fill.one": "Un riempimento che FubDraw non ha (una sfumatura, uno zigzag, dei punti) diventa il più vicino che ha.",
  "draw.import.note.fill.other": "{count} riempimenti che FubDraw non ha (sfumature, zigzag, punti) diventano i più vicini che ha.",
  "draw.import.note.tip.one": "Una punta di freccia si disegna diversa: piena invece che vuota, la più vicina che c’è, o nessuna.",
  "draw.import.note.tip.other": "{count} punte di freccia si disegnano diverse: piene invece che vuote, le più vicine che ci sono, o nessuna.",
  "draw.import.note.route.one": "Un connettore trova da sé il suo percorso: quello disegnato a mano non resta.",
  "draw.import.note.route.other": "{count} connettori trovano da sé il loro percorso: quelli disegnati a mano non restano.",
  "draw.import.note.stencil.one": "Una forma che FubDraw non ha si disegna come la più vicina, di solito un rettangolo.",
  "draw.import.note.stencil.other": "{count} forme che FubDraw non ha si disegnano come le più vicine, di solito rettangoli.",
  "draw.import.note.image.one": "Un’immagine resta fuori: sta fuori dal file, o in un formato che non si legge.",
  "draw.import.note.image.other": "{count} immagini restano fuori: stanno fuori dal file, o in un formato che non si legge.",
  "draw.import.note.reduced.one": "Un’immagine è rimpicciolita, perché il disegno stia nei suoi limiti.",
  "draw.import.note.reduced.other": "{count} immagini sono rimpicciolite, perché il disegno stia nei suoi limiti.",
  "draw.import.note.embed.one": "Un contenuto incorporato (una pagina web, un video) resta fuori.",
  "draw.import.note.embed.other": "{count} contenuti incorporati (pagine web, video) restano fuori.",
  "draw.import.note.link.one": "Un collegamento si perde: l’oggetto o il testo resta, ma non apre niente.",
  "draw.import.note.link.other": "{count} collegamenti si perdono: gli oggetti e i testi restano, ma non aprono niente.",
  "draw.import.note.unknown.one": "Un oggetto che non si sa leggere resta fuori.",
  "draw.import.note.unknown.other": "{count} oggetti che non si sanno leggere restano fuori.",
  "draw.import.note.html.one": "Un pezzo dell’aspetto di un testo (un’immagine, un apice, uno sfondo) resta fuori.",
  "draw.import.note.html.other": "{count} pezzi dell’aspetto dei testi (immagini, apici, sfondi) restano fuori.",
  "draw.import.note.shadow.one": "Un’ombra resta fuori: con le ombre, il disegno non sta nei suoi limiti.",
  "draw.import.note.shadow.other": "{count} ombre restano fuori: con le ombre, il disegno non sta nei suoi limiti.",
  "draw.import.note.placeholder.one": "Un segnaposto resta com’è scritto, senza un valore che lo riempia.",
  "draw.import.note.placeholder.other": "{count} segnaposto restano come sono scritti, senza un valore che li riempia.",
  "draw.import.error.format": "Questo file non è un disegno di Excalidraw né di draw.io.",
  "draw.import.error.empty": "Il file non ha niente da disegnare.",
  "draw.import.error.large": "Il disegno non sta nei limiti di un disegno di FubDraw: ha troppi oggetti, o troppe immagini anche rimpicciolite.",
  "draw.import.error.too_big": "Il file è troppo grande da importare: il massimo è {limit} MB.",
  "draw.import.error.read": "Il file non si legge: {reason}",
  "draw.import.error.convert": "Il disegno non si prepara: {reason}",
  "draw.import.error.name": "Il nome non va: {reason}.",
  "draw.import.error.write": "Il disegno non si scrive: {reason}",
  "draw.import.done": "Disegno importato in «{path}».",
} as const;

/// Una chiave del catalogo dell'importazione.
export type ImportKey = keyof typeof IT;

const EN: Readonly<Record<keyof typeof IT, string>> = {
  "draw.import.title": "Import drawing",
  "draw.import.from": "From “{file}”, a {program} drawing.",
  "draw.import.reading": "Reading the file…",
  "draw.import.preparing": "Preparing the drawing…",
  "draw.import.preview": "Preview of the imported drawing",
  "draw.import.name": "Name",
  "draw.import.folder": "Folder",
  "draw.import.folder.placeholder": "Vault root",
  "draw.import.create": "Import",
  "draw.import.count.shapes.one": "1 shape",
  "draw.import.count.shapes.other": "{count} shapes",
  "draw.import.count.texts.one": "1 text",
  "draw.import.count.texts.other": "{count} texts",
  "draw.import.count.lines.one": "1 line",
  "draw.import.count.lines.other": "{count} lines",
  "draw.import.count.ink.one": "1 freehand stroke",
  "draw.import.count.ink.other": "{count} freehand strokes",
  "draw.import.count.images.one": "1 image",
  "draw.import.count.images.other": "{count} images",
  "draw.import.count.boards.one": "1 board",
  "draw.import.count.boards.other": "{count} boards",
  "draw.import.count.layers.one": "1 layer",
  "draw.import.count.layers.other": "{count} layers",
  "draw.import.report": "What changes",
  "draw.import.report.none": "Everything comes in as it is.",
  "draw.import.note.sample": "For example: “{sample}”.",
  "draw.import.note.hand-font.one": "One text in a handwritten font switches to Inter.",
  "draw.import.note.hand-font.other": "{count} texts in a handwritten font switch to Inter.",
  "draw.import.note.rough.one": "One object with a sketchy stroke is drawn with a clean one.",
  "draw.import.note.rough.other": "{count} objects with a sketchy stroke are drawn with a clean one.",
  "draw.import.note.fill.one": "One fill FubDraw doesn’t have (a gradient, a zigzag, dots) becomes the closest one it has.",
  "draw.import.note.fill.other": "{count} fills FubDraw doesn’t have (gradients, zigzags, dots) become the closest ones it has.",
  "draw.import.note.tip.one": "One arrowhead is drawn differently: filled instead of hollow, the closest one available, or none.",
  "draw.import.note.tip.other": "{count} arrowheads are drawn differently: filled instead of hollow, the closest ones available, or none.",
  "draw.import.note.route.one": "One connector finds its own route: the hand-drawn one isn’t kept.",
  "draw.import.note.route.other": "{count} connectors find their own route: the hand-drawn ones aren’t kept.",
  "draw.import.note.stencil.one": "One shape FubDraw doesn’t have is drawn as the closest one, usually a rectangle.",
  "draw.import.note.stencil.other": "{count} shapes FubDraw doesn’t have are drawn as the closest ones, usually rectangles.",
  "draw.import.note.image.one": "One image is left out: it lives outside the file, or in a format that can’t be read.",
  "draw.import.note.image.other": "{count} images are left out: they live outside the file, or in a format that can’t be read.",
  "draw.import.note.reduced.one": "One image is scaled down so the drawing fits within its limits.",
  "draw.import.note.reduced.other": "{count} images are scaled down so the drawing fits within its limits.",
  "draw.import.note.embed.one": "One embedded item (a web page, a video) is left out.",
  "draw.import.note.embed.other": "{count} embedded items (web pages, videos) are left out.",
  "draw.import.note.link.one": "One link is lost: the object or text stays, but opens nothing.",
  "draw.import.note.link.other": "{count} links are lost: the objects and texts stay, but open nothing.",
  "draw.import.note.unknown.one": "One object that can’t be read is left out.",
  "draw.import.note.unknown.other": "{count} objects that can’t be read are left out.",
  "draw.import.note.html.one": "One piece of a text’s look (an image, a superscript, a background) is left out.",
  "draw.import.note.html.other": "{count} pieces of the texts’ look (images, superscripts, backgrounds) are left out.",
  "draw.import.note.shadow.one": "One shadow is left out: with shadows, the drawing doesn’t fit within its limits.",
  "draw.import.note.shadow.other": "{count} shadows are left out: with shadows, the drawing doesn’t fit within its limits.",
  "draw.import.note.placeholder.one": "One placeholder stays as written, with no value to fill it.",
  "draw.import.note.placeholder.other": "{count} placeholders stay as written, with no value to fill them.",
  "draw.import.error.format": "This file isn’t an Excalidraw or draw.io drawing.",
  "draw.import.error.empty": "The file has nothing to draw.",
  "draw.import.error.large": "The drawing doesn’t fit within the limits of a FubDraw drawing: too many objects, or too many images even when scaled down.",
  "draw.import.error.too_big": "The file is too big to import: the limit is {limit} MB.",
  "draw.import.error.read": "The file can’t be read: {reason}",
  "draw.import.error.convert": "The drawing can’t be prepared: {reason}",
  "draw.import.error.name": "The name won’t do: {reason}.",
  "draw.import.error.write": "The drawing can’t be written: {reason}",
  "draw.import.done": "Drawing imported to “{path}”.",
};

/// Il catalogo dell'importazione: `t` e `plural` come quelli della shell,
/// sulle chiavi sue.
export const importStrings = catalog(IT, { en: EN });
export const { t, plural } = importStrings;
